# Summary{-}

This rebuilding analysis is for the stock of `r spp` (_Sebastes caurinus_) in waters off California, south of Point Conception. The analysis is based on the 2021 stock assessment. The 2021 assessment model estimated the `r spp` south of Point Conception to be at 18.1 percent of the unexploited equilibrium spawning output at the beginning of 2021. This rebuilding analysis compares the results of applying a suite of potential management actions to the stock for 2023 and beyond.

The results of the analysis show that the value for $\text{T}_\text{MIN}$, the median year for rebuilding to the target level in the absence of fishing since the year of declaration (2023), is `r reb[[1]]$recovery[4] + reb[[1]]$tmin `. The estimated generation time for `r spp` was estimated to be `r reb[[1]]$mean_gen` years. $\text{T}_\text{MAX}$ is  `r reb[[1]]$tmax ` which is defined based on $\text{T}_\text{MIN}$ plus the mean generation time. The SPR harvest rate of `r reb[[1]]$rebuild_quants[6,2]`  generates a 50 percent probability of recovery by $\text{T}_\text{MID}$ where $\text{T}_\text{MID}$ was set equal to `r reb[[1]]$rebuild_quants[6,1]`, an intermediate year between $\text{T}_\text{MIN}$ and $\text{T}_\text{MAX}$.

