# Introduction

The 2021 assessment of `r spp` south of Point Conception in California documented that the stock had declined below the Minimum Stock Size Threshold (MSST), 25 percent of unfished spawning output for rockfish stocks, for the first time during the mid-1980s, remained below the MSST until 2011, increased above the MSST briefly between 2011-2016, but had fallen back below the MSST starting in 2017 [@wetzel_status_2021]. Based on the assumed stock productivity combined with the longevity of `r spp` a range of alternative rebuilding approaches were examined where the stock rebuilt to or above the management target of 40 percent ranging between `r reb[[1]]$recovery_spec[4] + reb[[1]]$tmin ` - `r reb[[1]]$tmax ` based on various SPR harvest rates from 0.55 - `r round(max(reb[[1]]$rebuild_quants[,2]),2) `. 


# Overview of the 2021 stock assessment

The 2021 assessment of `r spp` assessed the stock as four separate sub-stocks along the U.S. west coast: south of Point Conception in California, north of Point Conception in California, Oregon, and Washington.  This was the first assessment of `r spp` conducted within Stock Synthesis that used catch and length composition data to inform model estimates around stock size and status. The previous assessment of `r spp` conducted in 2013 was modeled using Extended Depletion-Based Stock Reduction Analysis (XDB-SRA), a delay-difference model, using catch, catch-per-unit-effort data, and prior distributions around biological parameters [@cope_data-moderate_2013]. The 2013 assessment estimated the stock at 76 percent of unfished spawning output based on fits to catch-per-unit-effort data and updated parameter distribution around biology (i.e., the posterior distributions). During model bridging between the 2013 to the 2021 assessment model, the large downward shift in estimated stock status in the new assessment was identified to be driven by the inclusion of the length data which implied a low relative stock size in recent years [@wetzel_status_2021]. 

The stock assessment for the sub-stock south of Point Conception in California assumed two fishing fleets, a commercial and a recreational fleet, along with one survey fleet, the Northwest Fisheries Science Center Hook and Line Survey (NWFSC HKL Survey). The majority of the removals and length composition data within the model arose from the recreational fleet. Total removals of `r spp` south of Point Conception peaked in the late 1970s and early 1980s, decreased from the late 1980s to mid-2000s but had high annual variability, and then increased in recent years (2013 - 2019).  The stock was modeled using Stock Synthesis as a two-sex age-structured model. Area specific length-at-age and fecundity-at-length for `r spp` south of Point Conception were estimated externally and then fixed within the model. Weight-at-length was estimated externally based upon observations by the NWFSC HKL and West Coast Groundfish Bottom Trawl Survey observations with the values fixed within the assessment model. Natural mortality and steepness were both fixed at the median or mean of the respective priors. The selectivity of both the commercial and recreational fishery were estimated to be domed-shape with the NWFSC HKL Survey selectivity fixed to be asymptotic. The assessment model decision table explore uncertainty around stock size and status using lower and higher log($R_0$) values relative to the base model.

\clearpage

# Management performance under rebuilding

This is the first rebuilding plan for `r spp ` off the coast of California south of Point Conception.

