# Rebuilding calculations

This rebuilding analysis was conducted using software developed by A. Punt (version 3.12h, August 2021). The steps followed were: 

\begin{itemize}
	\item Define how virgin spawning output ($\text{SB}_0$) will be calculated. 
	\item Define how future recruitment will be generated. 
	\item Define the fishery selectivity and allocation to be applied during rebuilding. 
	\item Decide how to include uncertainty in input parameters from the stock assessment in the rebuilding analysis. 
	\item Calculate rebuilding reference points from the most current assessment results 
	\begin{itemize}
		\item Calculate the projected year in which the stock would rebuild with a 50$\%$ probability if all future fishing mortality was eliminated ($\text{T}_\text{F}$=0).
		\item  Calculate the projected year for a 50$\%$ probability of rebuilding from the year in which the stock was first declared overfished ($\text{T}_\text{MIN}$). 
		\item Calculate the mean generation time. 
		\item Calculate the maximum allowable rebuilding time ($\text{T}_\text{MAX}$). 
	\end{itemize}
	\item Identification and analysis of alternative harvest strategies for rebuilding. 
\end{itemize}

## Definition of B0

The equilibrium spawning output ($\text{SB}_0$) used in this rebuilding analysis is calculated via the stock-recruitment relationship in order to be consistent with assessment model results. This level is estimated to be `r round(reb[[1]]$sb0,2)` mt in the base case assessment model, which dictates that the rebuilding target ($\text{SB}_{40\%}$) is `r round(reb[[1]]$sb40,2)` mt (Table \ref{tab:ref-points}). 

## Generation of future recruitment

The estimated parameters of the stock recruitment relationship (unexploited equilibrium recruitment [natural log of $R_0$], and steepness [$h$]) are used to generate future recruitments in the rebuilding analysis.  The 2021 assessment model did not estimate annual recruitment deviations but uncertainty around future recruitments was generated by assuming a recruitment variability of $\sigma_R = 0.60$.

## Fishery selectivity and allocation

The selectivity and weight at age used in the rebuilding analysis were obtained from 2021 assessment. The relative allocation of catch among fleets in this rebuilding analysis was informed using the allocation averaged over recent years (2015-2019).

## Inclusion of uncertainty

Uncertainty is included in this rebuilding analysis via 1,200 random simulations of stochastic future recruitment strengths and integration over the three states of nature across stock size (log($R_0$)). The base model was given 50% of the weight and each alternative state of nature was given 25% of the weight. 

## Rebuilding reference points

The 2021 and 2022 ACL removals were set at `r reb[[1]]$acl_matrix[1,2]` mt and `r reb[[1]]$acl_matrix[2,2]` mt, respectively. Given the estimated stock status an alternative analyses was conducted to evaluate rebuilding if the 2021 and 2022 removals were reduced to  `r reb[[2]]$acl_matrix[1,2]` mt, respectively. 

All reference points calculated based on this rebuilding analysis are given in Table \ref{tab:ref-points}. The minimum time required for rebuilding, $\text{T}_\text{MIN}$, with F=0 starting in 2023 was estimated to be `r reb[[1]]$tmin ` years, corresponding to the stock being rebuilt by `r reb[[1]]$recovery_spec[4] + reb[[1]]$tmin `, assuming the default removals for 2021 and 2022.  The estimated $\text{T}_\text{MIN}$ value decreased slightly to `r reb[[1]]$tmin ` years when the removals in in 2021 and 2022 were set lower (`r reb[[2]]$acl_matrix[1,2]` mt).  The mean generation time was estimated to be `r reb[[1]]$mean_gen ` years. The maximum time allowed for rebuilding, $\text{T}_\text{MAX}$, is defined as the $\text{T}_\text{MIN}$ plus the mean generation time for stocks that require more than 10 years to rebuild.  `r Spp` was unable to rebuild within 10 years so the estimated $\text{T}_\text{MAX}$ was `r reb[[1]]$tmax `. 

$\text{T}_\text{TARGET}$, $\text{SPR}_\text{TARGET}$ and $\text{P}_\text{MAX}$ are not specified since this is the first rebuilding plan for `r spp` and these values have not been set via the Council process. A rebuilding strategy is presented below based on rebuilding target year termed $\text{T}_\text{MID}$ which is set at `r reb[[1]]$rebuild_quants[6,1]`, mid-value between $\text{T}_\text{MIN}$ and $\text{T}_\text{MAX}$, along with the associatted $\text{SPR}_\text{MID}$. The Council may opt to select a $\text{T}_\text{TARGET}$ earlier or later that $\text{T}_\text{MID}$ given other factors.

## Alternate rebuilding strategies

Assuming that a constant rate of harvest will be applied throughout a rebuilding period, the basis for rebuilding alternatives can be divided into two approaches: 1) strategies based on selection of a harvest rate (SPR rate), or 2) strategies based selection of a $\text{T}_\text{TARGET}$ (year for 50% probability of recovery). This rebuilding analysis presents the following alternate strategies spread among the approaches based on the selection of a harvest rate or rebuilding by a selected target year:  

\begin{itemize}
	\item Apply a range of SPR values: 0.55, 0.60, 0.65, 0.70, and 0.75 
	\item Eliminate all harvest beginning in the next management cycle, 2023 (i.e., estimate $\text{T}_\text{F} = 0$).
	\item Apply the harvest rate that is estimated to lead to a 50$\%$ probability of recovery by $\text{T}_\text{MID}$ 
	\item Apply the ACL based on the 40:10 harvest control rule.
	\item Apply the ABC with time-varying $\sigma$.
\end{itemize}

The above rebuilding strategies were based on assuming removals of `r round(reb[[1]]$acl_matrix[1,2],2)` mt and `r round(reb[[1]]$acl_matrix[2,2],2)` mt in 2021 and 2022. 

Additional analyses were conducted to examine alternative rebuilding strategies. The first alternative applies the same rebuilding strategies as detailed above but a lower removal level in 2021 and 2022 of `r reb[[1]]$acl_matrix[2,1]` mt was assumed. The second alternative approach presents rebuilding strategies based on target rebuilding years an the associated $\text{SPR}_\text{TARGET}$ values.  The following years were examined:  2036, 2040, 2044, 2048, and 2052 ($\text{T}_\text{MAX}$). 