# Results

## Rebuilding reference points

Two alternative rebuilding scenarios were explored. The first set the 2021 and 2022 ACL removals at `r reb[[1]]$acl_matrix[1,2]` mt and `r reb[[1]]$acl_matrix[2,2]` mt, respectively, based on values provided by the Pacific Fishery Management Council Groundfish Management Team. The second analysis explored the impact on the rebuilding plan if removals in 2021 and 2022 were reduced to  `r reb[[2]]$acl_matrix[1,2]` mt for both years. The following reference points reported below are based on assumed full removals of `r reb[[1]]$acl_matrix[1,2]` and `r reb[[1]]$acl_matrix[2,2]` mt in 2021 and 2022.  The reference points based on assuming lower removals in 2021 and 2022 are presented as sensitivities later in the results section.

All reference points calculated based on this rebuilding analysis are given in Table \ref{tab:ref-points}. The minimum time required for rebuilding, $\text{T}_\text{MIN}$, with no fishing (F=0) starting in 2023 was estimated to be `r reb[[1]]$tmin ` years, corresponding to the stock being rebuilt by `r reb[[1]]$recovery_spec[4] + reb[[1]]$tmin `, assuming the default removals for 2021 and 2022.  The mean generation time was estimated to be `r reb[[1]]$mean_gen ` years. The maximum time allowed for rebuilding, $\text{T}_\text{MAX}$, is defined as the $\text{T}_\text{MIN}$ plus the mean generation time for stocks that require more than 10 years to rebuild.  `r Spp` was unable to rebuild within 10 years so the estimated $\text{T}_\text{MAX}$ was `r reb[[1]]$tmax `. 

## Alternative harvest projections

$\text{T}_\text{TARGET}$, $\text{SPR}_\text{TARGET}$ and $\text{P}_\text{MAX}$ are not specified since this is the first rebuilding plan for `r spp` and these values have not been set via the Pacific Fishery Management Council (Council) process. A rebuilding strategy is presented below based on rebuilding target year termed $\text{T}_\text{MID}$ which is set at `r reb[[1]]$rebuild_quants[6,1]`, mid-value between $\text{T}_\text{MIN}$ and $\text{T}_\text{MAX}$, along with the associated SPR harvest rate. The Council may opt to select a $\text{T}_\text{TARGET}$ earlier or later than this $\text{T}_\text{MID}$ value based on fishery, economic, or other factors.

Summary results from the rebuilding alternatives assuming removals of `r reb[[1]]$acl_matrix[1,2]` and `r reb[[1]]$acl_matrix[2,2]` mt are presented in Table \ref{tab:reb-options}. Summaries of the additional alternative based on reduced removals in 2021 and 2022 are presented in Table \ref{tab:reb-options-catch} and rebuilding alternatives based on various target years are presented in Table \ref{tab:reb-options-year}.

The target rebuilding year based on the range of pre-specified SPR values between 0.55 - 0.75 ranged from 2036 - 2046 (Table \ref{tab:reb-options}). The probability of rebuilding by year steadily increased across the alternative SPR values with full rebuilding by 2046 when the lowest SPR of 0.55 was applied (Table \ref{tab:prob-mat} and Figure \ref{fig:prob-fig}). The recommended removals in 2023, the first year of rebuilding, were low ranging between `r min(round(reb[[1]]$acl_matrix[3,2:6],2))` - `r max(round(reb[[1]]$acl_matrix[3,2:6],2))` mt across alternative SPR values (Table \ref{tab:acl-mat}) with the recommended removals slowly increasing by year during the rebuilding period (Figure \ref{fig:acl-fig}). The estimated Overfishing Limits (OFLs) for each rebuilding alternative is given in Table \ref{tab:ofl-mat}. The change in spawning output by year relative to the spawning output target, 40% of unfished, under each of the alternative SPR values are shown by year in Table \ref{tab:rel-ssb-mat} and Figure \ref{fig:rel-ssb-fig}).

The "ABC Rule" projections were based on the adopted rockfish SPR target of 0.50 combined with a time-varying $\sigma$ and category 2 $P^*$.  The stock was estimated to rebuild by year `r reb[[1]]$rebuild_quants$Ttarget[9]` with a probability of `r reb[[1]]$rebuild_quants$Prebuild[9]` (Table \ref{tab:reb-options}). Rebuilding by $\text{T}_\text{MID}$, `r reb[[1]]$rebuild_quants[6,1]`, was achieved using a SPR value of `r reb[[1]]$rebuild_quants[6,2]` (Table \ref{tab:reb-options}) with a `r reb[[1]]$rebuild_quants[6,3]` probability of rebuilding by $\text{T}_\text{MAX}$, `r reb[[1]]$tmax` (Table \ref{tab:prob-mat}). 

Reducing the assumed removals in 2021 and 2022 had only a limited impact on the estimated rebuilding by SPR rate (Table \ref{tab:reb-options-catch}). Reducing the removals in 2021 and 2022 decreased the minimum time for rebuilding ($\text{T}_\text{MIN}$) to `r reb[[2]]$recovery_spec[3] + reb[[2]]$tmin `, two years earlier compared to the initial rebuilding alternatives.  The reduction of the $\text{T}_\text{MIN}$ resulted in a decrease in the $\text{T}_\text{MAX}$ to `r reb[[2]]$tmax`. The probability of rebuilding, annual catches, OFLs, and relative spawning outputs by year are shown in Tables \ref{tab:prob-mat-catch} - \ref{tab:rel-ssb-mat-catch}. 

The final alternative rebuilding analysis that examined a range of specific rebuilding target years (Table \ref{tab:reb-options-year}) generally fell within alternatives explored in the initial analysis (Table \ref{tab:reb-options}) but provided additional granularity to see potential rebuilding timelines.  The probability of rebuilding, annual catches, OFLs, and relative spawning output by year are shown in Tables \ref{tab:prob-mat-year} - \ref{tab:rel-ssb-mat-year}. 
