## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in Table \ref{tab:referenceES}. Estimates of stock size and status over time are shown in Table \ref{tab:timeseries}. 

### Parameter Estimates{#para-estimates}

Estimated parameter values are provided in Table \ref{tab:params}. The log($R_0$) was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. The selectivity was fixed to be asymptotic for the commercial fleet with a peak in maximum selectivity for fish at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_OR_Commercial(1)', 'Value'], 1)` cm.  The estimate of the peak selectivity was highly sensitive to which years of commercial data were used and whether recruitment deviations were estimated.  Early years of the commercial data have large observations of small fish, likely due to a large late-1990s year class, resulting in a wide range of observed lengths across all years for this fleet. If recruitment deviations were estimated the model was able to fit these observations of small fish with large recruitment deviations and estimating selectivity to be highly right-shifted (selectivity peak at 49.7 cm). However, there appeared to be limited information in the length data regarding recruitment, aside from a few select years in the late 1990s. If recruitment was estimated to be deterministic (recruitment deviations equal to 0) the estimated peak selectivity for the commercial fleet was poorly informed. Depending upon the parameter starting value, the model would either estimate a relatively small size for peak selectivity (32 cm to fit the high proportion of small fish observed in select years) or a larger peak (45 cm an upward). To stabilize the estimation of the commercial selectivity years with high observations of small fish and were not considered indicative of the overall selectivity pattern were removed (1999 - 2002, 2017). The estimated peak of selectivity of `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_OR_Commercial(1)', 'Value'], 1)` cm was consistent with *a priori* expectations of the general size of `r spp` observed in the commercial fleet (Troy Buell and Brett Rodomsky, ODFW, personal communication). However, the base model estimate around commercial peak selectivity was uncertain with the 95 percent asymptotic intervals ranging from `r paste(round(peak_low,1), "-", round(peak_high,1))` cm. Sensitivity to the shape of the commercial selectivity with recruitment deviations estimated were explored as sensitivities (see Section \ref{sensitivities} for details) with a profile across the peak parameter provided in the Section \ref{like-profiles}.       

The selectivity for the recreational fleet was estimated to be dome-shaped at the largest sizes. The peak of the selectivity curve by the recreational fleet was estimated to be `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_OR_Recreational(2)', 'Value'], 1)` cm. Sensitivities to the shape of the recreational selectivity were explored (see Section \ref{sensitivities} for details). The limited dome-shape in selectivity could arise due to targeting of other species.  Often recreational fishing at deeper depths, where the  largest `r spp` are likely to occur, are targeting of lingcod. Targeting lingcod using larger hooks and/or baiting hooks with herring would likely preclude catching larger `r spp`. 


### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets.  The Pearson residuals for the commercial fishery are low overall, with a possible pattern of observations exceeding expected values above 40 cm between 2007 - 2014 (Figure \ref{fig:com-pearson}). The mean lengths observed by the commercial fishery range between 41 - 45 cm across years and with the model expected mean length flat across years (Figure \ref{fig:com-mean-len-fit}). 

The Pearson residuals were relatively small (max residual size of 4.79) for the recreational length data but patterns were  variable by year and sex (Figure \ref{fig:rec-pearson}). There was a solid block of observations that exceeded model expectations (solid bubbles) between 20 - 40 cm from 2000 - 2004 which, based on the length-at-age, could indicate one or more above average recruitment events in the 1990s. This pattern of residuals continues in later years where there where the observations were greater than the model expectations for sizes above 40 cm. Throughout the mid-2000s the mean length shifts to a larger size (around 40 cm) with a decreased variation in the observed lengths (Figure \ref{fig:rec-mean-len-fit}). 

Detailed fits to the length data by year are provided in the Appendix, Section \ref{length-fit}. Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}.  The model fits the aggregated lengths for both the commercial and recreational fleet length data generally well.  The commercial fleet shows a slightly wider range of sizes compared to the recreational fleet, which has an aggregated peak around 45 cm approximately. Even when combined into unsexed composition data the aggregated commercial length data was noisy with multiple peaks in the data. The model overestimated the selectivity for fish between 35 - 42 cm and underestimated the peak around 47 cm. 

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The estimates of spawning output across time are uncertain with the base model estimating a spawning output of `r round(model$derived_quants[model$derived_quants$Label == 'SSB_2021','Value'], 2)` in 2021 with a 95 percent asymptotic interval ranging from `r paste(round(sb_low,2), "-", round(sb_high,2))` millions of eggs.  The predicted spawning output from the base model slowly begins declining in the early 1980s when catches from the commercial and recreational fleet began to increase (Figure \ref{fig:catch}). The population then continues to slowly decline, with slight increases in spawning output in 2016 and 2017 due to low removals in 2015 and 2016 (years where retention was prohibited in the recreational fishery). The estimate of total biomass over time is shown in Figure \ref{fig:tot-bio}.

The `r endyr` spawning output relative to unfished equilibrium spawning output is above the target of 40 percent of unfished spawning output (`r round(100*model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 1)` percent, Figure \ref{fig:depl}). Approximate confidence intervals based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output is relatively large ranging between approximately `r paste(round(100*dep_low,0), "-", round(100*dep_high,0))` percent of unfished. 

The slight dome shape in the final selectivity for the recreational fleet results in a small fraction of large fish being unavailable in recent years (Figure \ref{fig:unavail-bio}). The fraction of large fish unavailable is relatively small portion of the overall biomass and in theory would be available for selection by the commercial fishery.   

The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. 

