\clearpage
# Figures


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```	

<!-- ====================================================================== -->  
<!-- ******************           Map             ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(general_wd, "map.png"), 
caption = "Map of management area and assessments areas for copper rockfish with the assessment area for Oregon shown in purple",
label = 'map')
```

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	


<!-- ====================================================================== -->
<!-- ****************   Commercial Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page2.png"), 
caption = "Length composition data from the commercial fleet",
label = 'com-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Mean length for the commercial fleet with 95 percent confidence intervals",
label = 'mean-com-len-data')
```

<!-- ====================================================================== -->
<!-- **************** Recreational Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt0_page2.png"), 
caption = "Length composition data from the recreational fleet",
label = 'rec-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Mean length for the recreational fleet with 95 percent confidence intervals",
label = 'mean-rec-len-data')
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}

filein = file.path(general_wd,'figures_biology.Rmd')
read_child(filein)

```


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"),
caption = "Selectivity at length by fleet",
label = 'selex')
```

\clearpage

```{r, results = 'asis'}
#add_figure(
#filein = file.path(getwd(), "figs", "recdevs3_varcheck.png"),
#caption = "Asymptotic standard error estimate of recruitment deviations by years",
#label = 'rec-devs-se')
```

<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt0_page2.png"), 
caption = "Pearson residuals for the commercial fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'com-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Mean length for the commercial lengths with 95 percent confidence intervals based on current samples sizes",
label = 'com-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt0_page2.png"), 
caption = "Pearson residuals for the recreational fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Mean length for the recreational lengths with 95 percent confidence intervals based on current samples sizes",
label = 'rec-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps across all years by sex and for each fleet",
label = 'agg-len-fit')
```

<!-- ====================================================================== -->
<!-- ******************      Time Series       **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output",
label = 'ssb')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of relative spawning output",
label = 'depl')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figs", "unavailable_biomass.png"),
caption = "Proportion of biomass unavailable due to selectivity for small and large fish.",
label = 'unavail-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```



<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->


```{r, echo=FALSE, results='asis'}
sens_wd = file.path(substr(mod_loc, 1, 50), "_sensitivities", "_plots")
nm = paste0(substr(mod_loc, 52, 99), "_1_compare2_spawnbio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb-1')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(substr(mod_loc, 52, 99), "_1_compare4_Bratio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl-1')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(substr(mod_loc, 52, 99), "_1_compare12_recdevs_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated annual recruitment deviation",
label = 'sens-recdev-1')
```


```{r, echo=FALSE, results='asis'}
sens_wd = file.path(substr(mod_loc, 1, 50), "_sensitivities", "_plots")
nm = paste0(substr(mod_loc, 52, 99), "_2_compare2_spawnbio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb-2')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(substr(mod_loc, 52, 99), "_2_compare4_Bratio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl-2')
```

<!-- ====================================================================== -->
<!-- ******************      Likelihoods      ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'figures_likelihoods.Rmd')
read_child(filein)
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_Size_DblN_peak_OR_Commercial(1)"),  "piner_panel_Size_DblN_peak_OR_Commercial(1).png"), 
caption = "Change in the negative log-likelihood across a range of commercial peak selectivity values",
label = 'selex-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_Size_DblN_peak_OR_Commercial(1)"),  "Size_DblN_peak_OR_Commercial(1)_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of commercial peak selectivity values",
label = 'selex-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_Size_DblN_peak_OR_Commercial(1)"),  "Size_DblN_peak_OR_Commercial(1)_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of commercial peak selectivity values",
label = 'selex-depl')
```

\newpage

<!-- ====================================================================== -->
<!-- ******************       LB-SPR          ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}

add_figure(
filein = file.path(net_loc, "models", "lbspr", "Copper_OR_LBSPR_newVBGF.png"), 
caption = "LB-SPR yearly estimates of selectivity, the ratio of fishing intensity to natural mortality (F/M), and annual spawner-per-recruit (SPR) values",
label = 'lbspr')
```

\newpage

<!-- ====================================================================== -->
<!-- ******************       SSS             ***************************** --> 
<!-- ====================================================================== -->


```{r, echo=FALSE, results='asis'}
sss_loc = "C:/Assessments/2021/copper_rockfish_2021/models/sss/or/_plots"

add_figure(
filein = file.path(sss_loc, "10.5_base_depl_75_Priors.png"), 
caption = "Prior distributions for parameter input for SSS based on LB-SPR with fraction unfished in 2020 distributed around 75 percent",
label = "sss-prior-75")
```

\newpage

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sss_loc, "10.5_base_depl_75_quants.png"), 
caption = "Derived quantities from SSS run where fraction unfished in 2020 was assumed to be distribution around 75 percent",
label = "sss-quant-75")
```

\newpage

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sss_loc, "10.5_base_logistic_depl_47_Priors.png"), 
caption = "Prior distributions for parameter input for SSS based on asymptotic selectivity and a fraction unfished in 2020 distributed around 47 percent",
label = "sss-prior-47")
```

\newpage


```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sss_loc, "10.5_base_logistic_depl_47_quants.png"), 
caption = "Derived quantities from SSS run where fraction unfished in 2020 was assumed to be distribution around 47 percent",
label = "sss-quant-47")
```

\newpage

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sss_loc, "10.5_base_domed_depl_57_Priors.png"), 
caption = "Prior distributions for parameter input for SSS based on dome-shaped selectivity and a fraction unfished in 2020 distributed around 57 percent",
label = "sss-prior-57")
```

\newpage


```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sss_loc, "10.5_base_domed_depl_57_quants.png"), 
caption = "Derived quantities from SSS run where fraction unfished in 2020 was assumed to be distribution around 57 percent",
label = "sss-quant-57")
```

\newpage





<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'figures_retro.Rmd')
read_child(filein)
```

\clearpage


<!-- ====================================================================== -->
<!-- ******************     Comparison      ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'figures_compare.Rmd')
read_child(filein)
```

<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year",
label = 'phase')
```

\clearpage


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield')
```