## Fishery-Dependent Data


### Commercial Data

There are very limited commercial fishery removals of `r spp` off the Washington coast (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). Across all model years there were less than 2 mt removed by the commercial fishery. The commercial catches were provided directly by Washington Department of Fish and Wildlife (WDFW). Given the limited observed removals by the commercial fleet, the historical discards (discards prior to 2002) were assumed to be nominal and were not accounted for in the model. In recent years, 2002-2019, the coastwide discards observed by the West Coast Groundfish Observer Program (WCGOP) were attributed to each state based on the proportion of commercial removals by state.  The commercial discards allocated to Washington were relatively minor (less than 0.02 mt total since 2002).  There were no length data available for `r spp` in Pacific Fisheries Information Network (PacFIN) for use in this assessment.  


### Recreational / Sport Data

Recreational removals in the model begin in `r startyr` and are the primary source of fishing mortality for `r spp` (Figure \ref{fig:catch}). Removals were specified in numbers of fish (1,000s) and were converted to metric tons internally to the model  (Table \ref{tab:nums-mt}). Annual catches (in numbers) from the recreational fishery (1967, 1975-1980) were obtained from historical reports, and landings from 1990-2020 were obtained from WDFW Ocean Sampling Program (OSP) and Puget Sound Baseline Sampling Program (Puget Sound `r spp` samples not included in the data). To fill in the missing years, linear interpolations were used to find landed values between 1968 and 1974, and to bring catch down to zero in year 1934. Discard estimates are not available prior to 2002. Historical discards were estimated based on a discard to retained catch relationship from 2002 - 2020. Discard mortality by depth was applied to post-2001 discards estimate. Prior to 2002, a 31 percent mortality rate is applied to all discarded fish. The sum of retained and dead released `r spp` made up the total removal (in numbers) from the recreational fishery. The recreational removals generally increased over time, spiked in 2005 to an all-time high, and since have been roughly between 1,000 and 3,000 fish per year. 

Length compositions for the recreational fleet were available in 1979, 1981, 1982, 1983, and then each year from 1995 - 2020 (Table \ref{tab:len-samps}). The number of length observations by year were quite variable ranging between 3 - 463 samples per year (Figure \ref{fig:wa-len-data}). The size of sexed and unsexed fish observed by the recreational fleet were primarily between 30 - 45 cm (Figure \ref{fig:wa-len-agg}).  The mean length observed by year had limited variation with year with a marginally smaller mean length between 35 - 40 cm until 2010 after which the mean length increased slightly to range around 40 cm (Figure \ref{fig:mean-len-data}).     




