## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of stock size and status over time are shown in Table \ref{tab:timeseries}. 


### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The model estimated 3 total parameters: $R_0$ and two parameters associated with the recreational fleet selectivity.  The $R_0$ was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curve was estimated for the recreational fleet (Figure \ref{fig:selex}). The selectivity was fixed to be asymptotic, reaching maximum selectivity for fish at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_WA_Recreational(1)', 'Value'], 1)` cm.  The selectivity for the commercial fleet was assumed to be equal to the recreational fleet selectivity due to no available commercial length data.


### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the recreational fleet. The Pearson residuals show a pattern of greater observations of all sexes (unsexed, males, and females) that start around 1995 and appear to move through the length data by year, possibly indicating a strong or multiple strong recruitments entering the population (Figure \ref{fig:rec-pearson}). The base mode did not estimate annual recruitment deviations due to limited length data across recent years which may have allowed the model to better fit the data.  The mean lengths across years with data was relatively stable ranging roughly between 35 and 42 cm by year (Figure \ref{fig:rec-mean-len-fit}). 

Detailed fits to the length data by year are provided in [Appendix A](#append_a). Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}.  There are a few things that stand out when examining the aggregated length composition data. The estimated fits to the data by sex matches the general shape of the aggregated lengths, however, the model expects a higher proportion of the largest fish relative to the data.  This may indicate that the true selectivity of the recreational fleet may have some level of reduced selectivity of the largest fish (dome-shaped) but the selectivity in the model was fixed to be asymptotic to follow the pre-specified terms of reference for a length-based assessment which specifies that at least one fleet in the model should have asymptotic selectivity.   

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The predicted spawning output from the base model generally showed a slow decline over the timeseries with the spawning output stabilizing in recent years. The total biomass shows a similar slow decline across the modeled years (Figure \ref{fig:tot-bio}).

The `r endyr` spawning output relative to unfished equilibrium spawning output is above the target of 40% of unfished spawning output (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`, Figure \ref{fig:depl}). Approximate confidence intervals based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output is limited. The standard deviation of the log of the spawning output in `r endyr` is `r round(model$Pstar_sigma, 2)`.

The stock-recruit curve resulting from a value of steepness fixed at `r print(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. The estimated annual recruitment is shown in  Figure \ref{fig:recruits}


### Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40% of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr` spawning output relative to unfished equilibrium spawning output is above the target of 40% of unfished spawning output (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, has bounced above and blow the harvest rate limit ($SPR_{50\%}$) in recent years (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.
