## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered by 10 percent. This was repeated 100 times, with 94 out of 100 runs returned to the base model likelihood. A better, lower negative log-likelihood, model fit was not found. The model did not experience convergence issues when provided reasonable starting values. Through the jittering done as explained and likelihood profiles, we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian. 

### Sensitivity Analyses{#sens}

Several sensitivity analyses were conducted.  The majority of the sensitivities conducted was a single exploration from the base model assumptions and/or data, and were not performed in a cumulative fashion.

\begin{enumerate}

  \item Estimate female natural mortality ($M$).
  
  \item Estimate female growth coefficient ($k$).

  \item Estimate female $L_{\infty}$. 
    
  \item Estimate annual recruitment deviations. 

  \item Estimate annual recruitment deviations while allowing for a dome-shaped selectivity curve. 
  
  \item Data weighting according to the McAllister-Ianelli (MI DW) method using the weighting values shown in Table \ref{tab:dw}. 

  \item Data weighting according to the Francis method using the weighting values shown in Table \ref{tab:dw}. 
  
  \item Data weighting according to the Dirichlet-Multinomial (DM DW) method where the estimated parameters are shown in Table \ref{tab:dw}. 
  
\end{enumerate}

Likelihood values and estimates of key parameters from each sensitivity are available in Table \ref{tab:sensitivities}.  Plots of the estimated time-series of spawning biomass and relative spawning biomass are shown in Figures \ref{fig:sens-ssb} and \ref{fig:sens-depl}.

The two sensitivities that had the largest impact relative to the base model were those that estimated annual recruitment deviations alone or combined to also estimate dome-shaped selectivity (Figures \ref{fig:sens-ssb} and \ref{fig:sens-depl}). The time series of each of these sensitivities resulted in large scale swings in spawning output across time. The estimates or recruitment deviations had a string of average estimates during the late 1990s and early 2000s then switched to a period of low recruitment success in recent years (Figure \ref{fig:sens-recr}). The recruitment deviation estimates were likely being driven by subtle shifts in the mean lengths being observed across time (Figure \ref{fig:mean-len-data}). The pattern of recruitment deviations estimated was extreme for the Washington area model but the general pattern showed some coherence with the recruitment deviations peaks estimated in the separate Oregon area model (shown as a sensitivity). The sensitivity in the Oregon model that estimated recruitment deviations also estimated above average recruitment in the late 1990s which led to an increase in spawning output during the 2000s similar to what was observed in this sensitivity for the Washington model.  This may indicate that `r spp` off the coast of Oregon and Washington experience similar drivers in recruitment.     

A sensitivity run allowing dome-shaped selectivity with deterministic recruitment was also performed but not shown due to the model failing to estimate a reasonable biomass scale (hit the upper bound of log($R_0$) of 20). 

The sensitivities exploring data weighting using the Francis or MI methods matched the base model as expected given that there was only one source of data used in the model. In contrast, the DM method resulted in a stock size and status less than the base model.  It is unclear why this difference in results across data weighting arose.  


### Likelihood Profiles

Likelihood profiles were constructed for $R_0$, steepness, female natural mortality, female $L_{\infty}$, female growth coefficient ($k$), and female coefficient of variation for older fish ($CV_2$) values separately. These likelihood profiles were constructed by fixing the parameter at specific values and estimating the remaining parameters based on the fixed parameter value.

In regards to values of $R_0$, the negative log-likelihood was minimized at approximately log($R_0$) of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),2)` (Figure \ref{fig:r0-profile}). Increasing the $R_0$, relative to the value estimated, results in an increase in stock scale and status (Figures \ref{fig:r0-ssb} and \ref{fig:r0-depl}). 

For steepness, the negative log-likelihood supported values at the upper bound of 1.0 (Figure \ref{fig:h-profile}).  Assuming higher or lower steepness values impacted the estimated unfished spawning output but had less impact on the final spawning output (Figure \ref{fig:h-ssb}). The estimated relative final stock status ranged between around the minimum threshold (0.25) to above the management target depending upon assuming a lower or higher steepness value (Figure \ref{fig:h-depl}).

The negative log-likelihood profile across female natural mortality supported values greater than the fixed value of `r model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1","Value"]` yr^-1^ (Figure \ref{fig:m-profile}). The estimate stock trajectories assuming lower or higher natural mortality values impacted the estimated unfished spawning output and resulted in stock statuses within the management precautionary zone (between 0.25 - 0.40) and above (Figures \ref{fig:m-ssb} and  \ref{fig:m-depl}). 

A profile across a range of female $L_{\infty}$ values was also conducted (Figure \ref{fig:linf-profile}).  The negative log-likelihood showed support for values between 46 and 47 cm. The $L_{\infty}$ value for female fish in the model was fixed at `r model$parameters[model$parameters$Label == "L_at_Amax_Fem_GP_1","Value"]` cm based on length-at-age data collected off the Oregon and Washington coasts. The stock scale and status is quite variable across alternative $L_{\infty}$ values where assuming lower values resulted in sharp increases in stock scale and status (Figures \ref{fig:linf-ssb} and \ref{fig:linf-depl}).

A profile across a range of female $k$ values was also conducted (Figure \ref{fig:k-profile}).  The negative log-likelihood showed support for values between 0.11 and 0.13 yr^-1^. The $k$ value for female fish in the model was fixed at `r model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1","Value"]` yr^-1^ based on length-at-age data collected off the Oregon and Washington coasts. The stock scale and status increases under lower $k$ values where assuming higher values resulted in decreases in stock scale and status (Figures \ref{fig:k-ssb} and \ref{fig:k-depl}).

The profile across a range of $\text{CV}_2$ for older females supported lower $\text{CV}_2$ values (Figure \ref{fig:cv-profile}). Assuming lower $\text{CV}_2$ values increased the estimated spawning output but had limited impact in the estimate of fraction unfished (Figures \ref{fig:cv-ssb} and \ref{fig:cv-depl}).

### Length-Based Spawner-per-Recruit Analysis

An exploratory length-based spawner-per-recruit analysis using the approach developed by Hordyk et al. [-@hordyk_novel_2015] was conducted. This approach assumes asymptotic selectivity and deterministic recruitment to produce independent estimates by year of selectivity and spawner-per-recruit (SPR) effort based on the observed recreational lengths. This analysis indicated that `r spp` were 50 percent selected generally between 30 - 35 cm (excluding 2018) with full selection between 35 - 40 cm  (Figure \ref{fig:lbspr}). The median estimates of SPR by year ranged between 0.60 - 0.75 between 2016 - 2019 with an average of the medians of 0.67. This type of analysis can provide insight on the fishing effort based on life history and observed length data in the absence of an integrated assessment model.  

An additional analysis to estimate stock status based on length data alone was conducted within a length only version of Stock Synthesis. Within this approach the removal history is removed but the same life history values, selectivities, and length compositions (both sexed and unsexed) are used. The underlying assumption is that the population has gone through an aggregate constant catch and constant recruitment to get an estimate of the current stock status. Length compositions are fit by estimating the parameter log($R_0$) (considered a nuisance parameter), which allows for best fits to the length comps and the selectivity by fleet. Using the recreational lengths, the estimated logistic selectivity, and life history from the Washington base model the implied stock status in 2020 was estimated to be approximately 0.44.

The estimates of the SPR harvest rate by year and the length only version of Stock Synthesis were used to provide external estimates of stock status in 2020 for two Simple Stock Synthesis (SSS) analysis.   

### Simple Stock Synthesis

A SSS was run to compare the results from the base model with a simpler modeling approach.  SSS samples via Monte Carlo from three key parameter distributions: natural mortality, steepness, and stock status in a specific year.  The mean and median of the priors assumed in the base model were used to create sampling distributions for natural mortality and steepness.  Two alternative assumptions regarding the distribution of current stock status were explored. SSS applies parameter draws from each of the three parameters within the model and then estimates an $R_0$ value based on the fixed removals and drawn parameters.   

\begin{enumerate}  
	\item Current stock status based on LB-SPR estimates: 
		\begin{itemize}
		\item Number of draws = 1,000,
		\item $M$ = lognormal ($\mu$ = 0.108 yr$^{-1}$, $\sigma$ = 0.22),
		\item $h$ = truncated beta ($\alpha$ = 0.72, $\beta$ = 0.15, a = 0.20, b = 1.0), and
		\item Fraction unfished in `r endyr` = beta($\alpha$ = 0.67, $\beta$ = 0.20)	
	\end{itemize}
	\item Current stock status based on the estimate from length only Stock Synthesis:
	\begin{itemize}
		\item Number of draws = 1,000,
		\item $M$ = lognormal distribution ($\mu$ = 0.108 yr$^{-1}$, $\sigma$ = 0.22),
		\item $h$ = truncated beta ($\alpha$ = 0.72, $\beta$ = 0.15, a = 0.20, b = 1.0), and
		\item Fraction unfished in `r endyr` = beta($\alpha$ = 0.44, $\beta$ = 0.20)
	\end{itemize}	
\end{enumerate}

The median of unfished spawning output, spawning output `r endyr+1`, fraction unfished in `r endyr+1`, the OFL in `r endyr + 3`, and the ABC in `r endyr + 3` based on the `r endyr +1` fraction unfished of 67 percent is shown in in Table \ref{tab:SSS-67}. The prior distribution for the parameters and the derived quantities with 95 percent uncertainty are shown in Figures \ref{fig:sss-prior-67} and \ref{fig:sss-quant-67}. Assuming that the stock was less depleted relative to the base model resulted in higher estimates of the OFL and ABC in 2023, even when the category 3 buffer was applied (buffer = 0.778, based on a P* = 0.45 and $\sigma4 = 2.0).  

The median of unfished spawning output, spawning output `r endyr+1`, fraction unfished in `r endyr+1`, the OFL in `r endyr + 3`, and the ABC in `r endyr + 3` based on the `r endyr +1` fraction unfished of 44 percent is shown in in Table \ref{tab:SSS-44}. The prior distribution for the parameters and the derived quantities with 95 percent uncertainty are shown in Figures \ref{fig:sss-prior-44} and \ref{fig:sss-quant-44}. Assuming a stock status similar to the base model, SSS resulted in an OFL and ABC values that were marginally lower due to the larger buffer applied in the SSS model (base model OFL in `r endyr + 3` = `r round(model$derived_quant[model$derived_quant$Label == "OFLCatch_2023", 2], 2)`, ABC in `r endyr + 3` = `r round(model$derived_quant[model$derived_quant$Label == "ForeCatch_2023", 2], 2)`).  

### Retrospective Analysis
A five-year retrospective analysis was conducted by running the model using data only through 2015, 2016, 2017, 2018, 2019 and 2020. The estimated spawning output was consistent with the base model when recent data were removed up but estimated a lower stock size and status relative to the base model when the last 3-5 years of data were removed (Figures \ref{fig:retro-ssb} and \ref{fig:retro-depl}). 


### Comparison with Other West Coast Stocks

```{r, echo=FALSE, results='asis'}
general_wd = "C:/Assessments/2021/copper_rockfish_2021/write_up/general_text"
filein = file.path(general_wd,'diag_area_compare.Rmd')
read_child(filein)
```