## Basic Information

This assessment reports the status of `r spp` (*Sebastes caurinus*) off the U.S. West Coast using data through 2020. `r Spp` is a medium- to large-sized nearshore rockfish found from Mexico to Alaska.  The core range is comparatively large, from northern Baja Mexico to the Gulf of Alaska, as well as in Puget Sound.   `r Spp` have historically been a part of both commercial (mainly in the live-fish fishery) and recreational fisheries throughout its range.  

## Life History

`r Spp` are commonly found in waters less than 130 meters in depth in nearshore kelp forests and rocky habitat [@love_milton_probably_1996]. The diets of `r spp` consist primarily of crustaceans, mollusks, and fish [@lea_biological_1999; @bizzarro_diet_2017-1]. The body coloring or `r spp` varies across the coast with northern fish often exibiting dark brown to olive  with southern fish exibiting yellow to olive-pink variations in color [@miller_guide_1972] which initially led to them being designated as two seperate species (*caurinus* and *vexillaris*). 

Numerous genetic studies have been performed looking for genetic variation in `r spp` with variable outcomes. Genetic work has revealed significant differences between Puget Sound and coastal stocks of `r spp` [@dick_replicate_2014]. Stocks along the West Coast have not been deteremined to be genetically distinct populations but significant population sub-division has been detected along the indicating limited oceanographic exchange among geographically proximate locations [@buonaccorsi_population_2002; @johansson_influence_2008]. A specific study examining `r spp` populations off the coast of Santa Barbara and Monterey California identified a genetic break between the north and south with moderate differentiation [@sivasundar_life_2010].

`r Spp` is a relatively long-lived rockfish and have been estimated to live at least 50 years [@love_milton_probably_1996]. `r Spp` was determined to have the highest vulnerability (V = 2.27) of any West Coast groundfish based on recent productivity susceptibility analaysis [@cope_approach_2011].  

## Ecosystem Considerations
Replace text.

