```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "piner_panel_SR_LN(R0).png"), 
caption = "Change in the negative log-likelihood across a range of log(R~0~) values",
label = 'r0-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of log(R~0~) values",
label = 'r0-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of log(R~0~) values",
label = 'r0-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "piner_panel_SR_BH_steep.png"), 
caption = "Change in the negative log-likelihood across a range of steepness values",
label = 'h-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of steepness values",
label = 'h-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of steepness values",
label = 'h-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "piner_panel_NatM_p_1_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female natural mortality values",
label = 'm-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female natural mortality values",
label = 'm-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female natural values",
label = 'm-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "piner_panel_L_at_Amax_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female maximum length values",
label = 'linf-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female maximum length values",
label = 'linf-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female maximum length values",
label = 'linf-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "piner_panel_VonBert_K_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female k values",
label = 'k-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female k values",
label = 'k-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female k values",
label = 'k-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_CV_old_Fem_GP_1"),  "piner_panel_CV_old_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female coefficient of variation for older ages",
label = 'cv-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_CV_old_Fem_GP_1"),  "CV_old_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female coefficient of variation for older ages",
label = 'cv-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_CV_old_Fem_GP_1"),  "CV_old_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female coefficient of variation for older ages",
label = 'cv-depl')
```


