## Fishery-Dependent Data

### Commercial Fishery

#### Landings

The commercial removals were extracted from the The Pacific Fisheries Information Network (PacFIN) database for 1981-2020 on February 21, 2021.  Commercial removals for `r spp` were combined into a single fleet by aggregating across gear types and fish landed live or dead (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). The grouping of all commercial landings into a single fleet was driven by the limited length composition data available per gear type.  Additionally, commercial length data available in PacFIN database for California did not have the needed information to identify samples from live versus dead fish (i.e., condition code) preventing the ability to evaluate the data based on live versus dead landing.  

Commercial landings prior to 1969 were extracted from the SWFSC catch reconstruction database for estimates from the California Catch Reconstruction [@ralston_documentation_2010]. Landings in this database are divided into trawl, non-trawl, and unknown gear categories. Regions 7 and 8 as defined by Ralston et al. [-@ralston_documentation_2010] were assigned to Southern California. Region 6 in Ralston et al. [-@ralston_documentation_2010] includes Santa Barbara County (mainly south of Point Conception), plus some major ports North of Point Conception. Catches from Region 6 were allocated to the areas north and south of Point Conception following an approach developed by Dick et al. [-@dick_status_2007] for the assessment of cowcod. Specifically, port-specific landings of total rockfish from the California Department of Fish and Wildlife (CDFW) Fish Bulletin series were used to determine the annual fraction of landings in Region 6 that was south of Point Conception (Table \ref{tab:com-ratio}). Rockfish landings at that time were not reported at the species level. Although the use of total rockfish landings to partition catch in Region 6 is not ideal, this was the best available option given the absence of port-specific species composition data. Years with no data were imputed using the average of ratio estimates from adjacent years. Annual catches from unknown locations and unknown gear types were allocated proportional to the catches from known regions and gears. Catches from known regions, but unknown gears, were allocated proportional to catches by known gears within the same region. In this way, total annual removals in California were kept consistent with those reported by Ralston et al. [-@ralston_documentation_2010], and assigned to the assessment areas north and south of Point Conception.

In September 2005, the California Cooperative Groundfish Survey (CCGS CALCOM) incorporated newly acquired commercial landings statistics from 1969-1979 into the CALCOM database. The data consisted of landing receipts ("fish tickets"), including mixed species categories for rockfish. In order to assign rockfish landings to individual species, the earliest available species composition samples were applied to the fish ticket data by port, gear, and quarter. These 'ratio estimator' landings are coded (internally) as market category 977 in the CALCOM database, and are used in this assessment, as they have in past assessments as the best available landings for the time period 1969 - 1979 for all port complexes.  See Appendix A of Dick et al. [-@dick_status_2007] for further details.
 
Commercial fishery landings from 1981-2020 were extracted from the PacFIN (extracted 2/22/2021). Landings were separated for the area north of Point Conception based on port of landing. The input catches in the model represent total removals: landings plus discards. Discards totals for the commercial fleet from 2002 - 2019 were determined based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide WCGOP discards were allocated to state and area based on the total observed landings by WCGOP. An average commercial discard mortality rate of 4.4 percent, based on the WCGOP data from 2002 - 2019, was applied to adjust historical landings data to account for total removals 

#### Length Compositions 

Biological data were extracted from the PacFIN Biological Data System on February 21, 2001. The quantity of length samples from the commercial fishery were low until 1991 (Table \ref{tab:com-len-samps}). Due to low annual sample sizes, years prior to 1991 were not used in model fitting (entered as a 'ghost fleet' observations to see the implied fit). When used during model development, the noisy distribution of years with low sample size prior to 1991, impacted the estimation of selectivity, reducing the fits to the later more informed data years. Length samples were highest during the 1990s, while the number of lengths samples by year have been relatively low since 2002. The range of sizes observed from 1991 - 2007 was relatively broad, encompassing approximately 25 - 54 cm (Figure \ref{fig:com-len-data}).  Since 2008, the frequency of sizes observed has shifted to smaller lengths, centered around 30 cm, with larger fish still being observed in the data. This shift in observed sizes is also reflected in the mean lengths observed by year (Figure \ref{fig:mean-com-len-data}), which could be due to shifts in fishery behavior, changes in the population demographics (e.g., incoming strong recruitments), or a combination of multiple factors. 

The input sample sizes were calculated via the Stewart method (Ian Stewart, personal communication) based on a combination of trips and fish sampled:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}


### Recreational Fishery

#### Landings

The recreational fishery is the main source of exploitation of `r spp`. Recreational catches of `r spp` in California waters north of Point Conception peaked in the late 1970s and early 1980s. Removals declined sharply in the 1990s and early 2000s.  The removals remained relatively low until 2015.  

Recreational removal estimates from 1928 to 1980 were obtained from the historical reconstruction [@ralston_documentation_2010], which were available split north and south of Point Conception. Recreational removals from 1981 - 1989 and 1993 - 2003 were obtained from Marine Recreational Fisheries Statistics Survey (MRFSS). MRFSS includes estimates of removals for 1980. However, due to inconsistencies in the estimates of this year in MRFSS, likely due to it being the first year of the survey with low sample sizes, the value for recreational removals from Ralston et al. [-@ralston_documentation_2010] was used. 

The MRFSS definition of "Southern California" included San Luis Obispo County from 1981 - 1989, requiring the catches from this county to be split out and added to recreational removals for north of Point Conception. Albin et al. [-@albin_effort_1993] used MRFSS data to estimate catch at a finer spatial scale from the California/Oregon border to the southern edge of San Luis Obispo County. The ratio of catches (0.316) in San Luis Obispo to the total removals calculated based on the data from Albin et al. [-@albin_effort_1993] was estimated and used to adjust the MRFSS catches to account for all removals north of Point Conception. 

There are three years without removals, 1990 - 1992, available in the MRFSS data. Removals for the missing years were filled in by applying a linear ramp in removals between the 1989 and 1993 values. 

Recreational catches from 2004 - 2020 were obtained from California Recreational Fisheries Survey (CRFS available on the Recreational Fisheries Information Network, RecFIN). Both data sources, MRFSS and CRFS, provide total mortality which combined observed landings plus estimates of discarded fish.  

The recreational removals from the historical reconstruction from 1928 - 1980 account for only landed fish. A historical discard rate of 3 percent based on Miller and Gotshall [-@miller_ocean_1965] was used to estimate total catches for this period. MRSS and CRFS each provide estimates of total mortality so no additional discard assumptions were made. 


#### Length Compositions

Length data for retained catch for MRFSS (1980-2003) and CRFS (2004-2019) were downloaded from the RecFIN website. The number of length observation by year are shown in Table \ref{tab:len-samps}. The highest number of samples occurred within the last 15 years of the modeled period. A broad range of sizes, between 20 - 50 cm, have been observed from the recreational fishery across available data years (Figure \ref{fig:rec-len-data}). The recreational length data show a pulse of smaller fish starting around 2010, which appears at greater lengths in subsequent years, perhaps indicating of a strong recruitment event.  The mean size observed across years ranged from 30 to approximately 38 cm (Figure \ref{fig:mean-rec-len-data}).

The input sample sizes were equal to the number of length samples available by year. 