## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in Table \ref{tab:referenceES}. Estimates of stock size and status over time are shown in Table \ref{tab:timeseries}. 

### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The $R_0$ was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. The commercial selectivity was estimated in two blocks `r startyr` - 2008 and 2009 - `r endyr`. The block in selectivity was aimed to capture the shift in observations of smaller fish in recent years (Figure \ref{fig:com-len-data}). The early block estimated a gradual slope of increasing selectivity across lengths with selectivity reaching 1.0 at the largest sizes with the parameter hitting the upper bound of 55 cm.  To reduce problems in convergence the final model fixed this parameter at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_N_Commercial(1)_BLK1repl_1916', 'Value'], 3)` cm, just below the upper bound. In recent years, commercial selectivity shifted left-ward resulting in increased selectivity of smaller fish with peak selectivity occurring at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_N_Commercial(1)', 'Value'], 2)` cm. The cause of this shift in selectivity is not entirely clear but may be related to the live-fish fishery which favors age 3 fish (Dan Platt, personal communication) combined with a strong recruitment event entering the fishery. Selectivity in the recreational fishery was assumed constant across the modeled period with maximum selectivity occurring for fish of `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_N_Recreational(2)', 'Value'], 1)` cm and greater. The peak selectivity for both fleets, commercial and recreational fishery, is less than the length-at-50 percent maturity (`r round(model$parameters[model$parameters$Label == 'Mat50%_Fem_GP_1', 'Value'], 2)` cm). 

The estimated annual recruitment and recruitment deviations are shown in  Figures \ref{fig:recruits} and \ref{fig:rec-devs}. A strong recruitment is estimated to have occurred in 2008 with 2009 and 2010 also being estimated to be well above average. While there could have been three above average recruitments occurring in subsequent years, alternatively there may have been a single year with high recruitment that the model is unable to accurately assign to a single year due to the variability in length data. Above average recruitment in 2008 has been estimated in other rockfish assessments off the West Coast [@gertseva_status_2015;@hicks_status_2015;@wetzel_status_2017]. The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. 

### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. Annual length composition fits are shown in [Appendix A](#append_a).  

The Pearson residuals for the commercial fishery length data area shown in Figure \ref{fig:com-pearson}. The observations of larger fish, greater than 45 cm, are minimally greater than the model expectations prior to 2009. Starting in 2009 the commercial length data shifts to smaller fish with observations greater than model expectations for fish between 25 - 30 cm. The mean length observed in the commercial lengths were generally stable between 1990 - 2003, slightly increasing between 2004 - 2007, and then decreasing to smaller sizes to a low in mean lengths occurring in 2011 (Figure \ref{fig:com-mean-len-fit}). The observed decline in mean lengths was not fit well by the model using only recruitment deviations, leading to the decision to also allow for a shift in commercial selectivity.  

The Pearson residuals for the recreational length data are variable by year (Figure \ref{fig:rec-pearson}). Pearson residuals were positive, observations greater than expected, for small fish prior to 1997 and are generally variable showing no clear misfit in the model in recent years. In model development, an additional selectivity block for years prior to 1997 were explored to address the pattern in the pearson residual. These model explorations did estimate a left-ward shift in selectivity for the recreational fleet by approximately 2-3 cm, but had little impact on the overall model results. In the aims of parsimony and simplicity a single selectivity pattern was assumed in the base model. The mean length by year for the recreational fleet was highly variable across years (Figure \ref{fig:rec-mean-len-fit}). The recreational lengths show a decrease in the mean length observed around 2011, similar to the commercial data.

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}.  The model fits the aggregated lengths for the recreational fleet length data generally well. The aggregated lengths for the commercial fleet reflected a wide selection across sizes with the model under-predicting the selection for both small and large fish. Multiple sensitivities were conducted to explore alternative parameterization of commercial selectivity. 

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The estimated spawning output decreases sharply in the mid-1970s reaching a low around 2000. The spawning output slowly increases between 2000 - 2010 with the rate of population growth increasing after 2011 as fish from recent strong classes begin to mature. The estimate of total biomass over time is shown in Figure \ref{fig:tot-bio}.

The model estimates that the spawning output relative the unfished equilibrium spawning output declined below the management limit of 25 percent around 1983 and remained below the limit until 2016 (Figure \ref{fig:depl}). The relative stock status at the start of `r endyr + 1` is estimated to be below the rockfish relative biomass target of 40 percent (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`) but above the management threshold of 25 percent.   


### Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr + 1` spawning output relative to unfished equilibrium spawning output is below the rockfish relative biomass target of 40 percent but greater that the management limit of 25 percent (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, was above the harvest rate limit ($SPR_{50\%}$) between the early 1970s and 2009, below the target between 2010 - 2016, and above the target in the final years of the model  (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.

