# Management 

## Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). The estimated sustainable total yields were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $\text{SPR}_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($\text{SB}_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_Btgt', 'Value'], 2)` million eggs. 

The estimated fraction unfished in `r endyr + 1` of `r round(100*model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 1)`  is just below the rockfish relative biomass management target of 40 percent (Figure \ref{fig:depl}). The fishing intensity, $1-\text{SPR}$, was above the harvest rate limit ($\text{SPR}_{50\%}$) between the early 1970s and late-2000s and has been both above and below the target over the final 10 years of the model (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). In recent years the stock status has been below the management target with the fishing intensity above and below the target in different years (Figure \ref{fig:phase}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.



## Harvest Projections and Decision Tables

A ten year projection of the base model with catches equal to the estimated Acceptable Biological Catch (ABC) based on the category 2 time-varying with $P^*$ = 0.45 for years 2023-2032 (Table \ref{tab:project}). Since the stock is estimated to be below the management target of 40 percent the buffer value in Table \ref{tab:project} reflects both the 40-10 harvest control rule adjustment and the time-varying scientific uncertainty buffer.

The area assumed in this assessment does not align with the PMFC management regions that define `r spp` ACL allocation, north and south of 40$^\circ$ 10' Lat. N. To determine the amount of the 2021 and 2021 ACL for the California portion of the stock north of Point Conception the total ACL that would be allocated to the state of California was determined by summing the S. 40$^\circ$ 10' Lat. N. ACL and the percent of the N. 40$^\circ$ 10' Lat. N. allocated to California (25 percent, PFMC Groundfish Management team personal communication). Once the total ACLs for California were determined the portion of the ACL allocated to the area north of Point Conception was based on the percentage of total removals in each area of California (north and south of Point Conception) from 2017 - 2019.  

The axes of uncertainty in the decision table is based on the uncertainty around the spawning biomass in `r endyr+1` ($\sigma$ = `r model$Pstar_sigma ` ) via natural mortality parameter. The $\sigma$ value was used to identify the 12.5 and 87.5 percentiles of the asymptotic standard deviation for the current year, `r endyr+1`, spawning biomass from the base model to identify the low and high states of nature (i.e., 1.15 standard deviations corresponding to the 12.5 and 87.5 percentiles). Once the `r endyr + 1` spawning biomass for the low and high states of nature were identified a search across natural mortality values were done to attain the current year spawning biomass values. The natural mortality values that corresponded with the lower and upper percentiles were 0.098 and 0.123^-y^.  

Across the low and high states of nature and across alternative future harvest scenarios the fraction of unfished ranges between 0.31 - 0.60 by the end of the 10 year projection period (Table \ref{tab:dec-tab}). The fraction unfished across the state of natures assuming the full ABC removals all increase over the projection period from the fraction unfished in 2023.


## Evaluation of Scientific Uncertainty

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'management_uncertainty.Rmd')
read_child(filein)
```

## Research and Data Needs

The ability to estimate additional process and biological parameters for `r spp` was limited by data. Collecting the following data would be beneficial to future assessments of the stock:

\begin{itemize}

	\item Both the recreational and commercial length data indicated that selection of `r spp` occurs at sizes that were below the length at 50 percent maturity assumed in the base model. Developing area specific estimates of the length- or age-at-maturity of `r spp` in California waters north of Point Conception would provide additional understanding of the potential impact of size selectivity by each fleet.

	\item Length samples could not be divided between live versus dead `r spp` for the commercial fishery data. This was due to issues with the California data in PacFIN (i.e., condition code not available). The ability to examine sample sizes and lengths from each type of landing would allow for future assessments to better account for the range of commercial fishing behavior.

	\item Otoliths should be or continue to be collected from both the commercial and recreational fisheries. Additional age data from both fishery-dependent and -independent sources would provide insight of area-specific growth of `r spp`.  These data would support future assessments and would also allow for assessments to better capture uncertainty through the estimation of growth parameters within the model. 

\end{itemize}