\clearpage
# Tables

## Rebuilding reference points and summary of alternatives

```{r, results = 'asis'}
# Rebuilding Reference Points Table
# Table 1
#==================================================================

quants = c(round(reb[[1]]$sb0,2), 
		   round(reb[[1]]$sb40, 2), 
		   round(reb[[1]]$sb_ass_year, 2),
		   reb[[1]]$recovery_spec[4],
		   reb[[1]]$recovery_spec[3], 
		   reb[[1]]$tmin + reb[[1]]$recovery_spec[4], 
		   reb[[1]]$mean_gen, 
		   reb[[1]]$tmax, 
		   "TBD",
		   "TBD")

row_names = c("SB0 (millions of eggs)", "SB40% (millions of eggs)", 
			"SB2021 (millions of eggs)", "Year rebuilding begins",
		    "Current year", "Tmin", "Mean generation time (years)", "Tmax", 
		    "Ttarget", "SPRtarget")

col_names = c("Parameter", "2021 Assessment Values")
out = cbind(row_names, quants)

table_format(x = out,
             caption = "Summary of the rebuilding reference points.",
             label = "ref-points",
             align = 'l',
             col_names = col_names)
```

\clearpage

```{r, results = 'asis'}
#==========================================================================
# Base Analysis Rebuilding Reference Points Table
# Table 2 
#=========================================================================

# All based on upcapped
#quants = rbind(round(reb[[1]]$acl_matrix[1:4,-1],2),
#		   reb[[1]]$rebuild_quants$SPR,
#		   reb[[1]]$rebuild_quants$Ttarget,
#		   rep(reb[[1]]$tmax, length(reb[[1]]$rebuild_quants$Ttarget)),
#		   reb[[1]]$rebuild_quants$Prebuild) # Prob by Tmax

# Franken-results to change out the ABC Rule run for the capped
quants = rbind(round(reb[[1]]$acl_matrix[1:4, 2:10], 2),
               reb[[1]]$rebuild_quants$SPR,
               reb[[1]]$rebuild_quants$Ttarget, 
               rep(reb[[1]]$tmax, length(reb[[1]]$rebuild_quants$Ttarget)),
               reb[[1]]$rebuild_quants$Prebuild) # Prob by Tmax

row_names = c("2021 Assumed Removals (mt)", 
			  "2022 Assumed Removals (mt)",
			  "2023 ACL (mt)", "2024 ACL (mt)", "SPR", "Ttarget", 
			  "Tmax",
			  "Probability of recovery by Tmax")

out = cbind(row_names, quants)
col_names = c("", colnames(out)[2:9], "ABC Rule")

table_format(x = out,
             caption = "Results of rebuilding alternatives based on selection of an SPR target or year for 50 percent probability of recovery based on the assumed removals for 2021-22. The SPR value for the ABC Rule is lower than 0.50 since this value represents the average SPR value applied across the projection period based on the time-varying buffer.",
             label = "reb-options",
             align = 'l',
             landscape = TRUE,
             col_names = col_names)
```


```{r, results = 'asis'}
#========================================================================================
# Alternative Target Years Rebuilding Reference Points Table
#========================================================================================

quants = rbind(round(reb[[2]]$acl_matrix[1:4, 2:10], 2),
               reb[[2]]$rebuild_quants$SPR,
               reb[[2]]$rebuild_quants$Ttarget, 
               rep(reb[[2]]$tmax, length(reb[[2]]$rebuild_quants$Ttarget)),
               reb[[2]]$rebuild_quants$Prebuild) # Prob by Tmax

row_names = c("2021 Assumed Removals (mt)", 
              "2022 Assumed Removals (mt)",
              "2023 ACL (mt)", "2024 ACL (mt)", "SPR", "Ttarget", 
              "Tmax",
              "Probability of recovery by Tmax")
out = cbind(row_names, quants)
col_names = c("", colnames(out)[-1])

table_format(x = out,
             caption = "Results of rebuilding alternatives based on alternative SPR harvest rates.",
             label = "reb-options-year",
             align = 'l',
             landscape = TRUE,
             col_names = col_names)
```


```{r, results = 'asis'}
#=========================================================================================
# Low Catch Alternative Rebuilding Reference Points Table
#=========================================================================================

#quants = rbind(round(reb[[2]]$acl_matrix[1:4,-1],2),
#		   reb[[2]]$rebuild_quants$SPR,
#		   reb[[2]]$rebuild_quants$Ttarget,
#		   rep(reb[[2]]$tmax, length(reb[[2]]$rebuild_quants$Ttarget)),
#		   reb[[2]]$rebuild_quants$Prebuild) # Prob by Tmax

# Franken-results to change out the ABC Rule run for the capped
# quants = rbind(cbind(round(reb[[2]]$acl_matrix[1:4, 2:9], 2), round(reb[[5]]$acl_matrix[1:4, 10], 2)),
#                c(reb[[2]]$rebuild_quants$SPR[1:8], reb[[5]]$rebuild_quants$SPR[9]),
#                c(reb[[2]]$rebuild_quants$Ttarget[1:8], reb[[5]]$rebuild_quants$Ttarget[9]),
#                rep(reb[[2]]$tmax, length(reb[[2]]$rebuild_quants$Ttarget)),
#                c(reb[[2]]$rebuild_quants$Prebuild[1:8], reb[[5]]$rebuild_quants$Prebuild[9])) # Prob by Tmax
# 
# row_names = c("2021 Assumed Removals (mt)", 
# 			  "2022 Assumed Removals (mt)",
# 			  "2023 ACL (mt)", "2024 ACL (mt)", "SPR", "Ttarget", 
# 			  "Tmax",
# 			  "Probability of recovery by Tmax")
# out = cbind(row_names, quants)
# col_names = c("", colnames(out)[2:9], "ABC Rule")
# 
# table_format(x = out,
#              caption = "Results of rebuilding alternatives based on alternative SPR targets resulting in 50 percent probability of recovery by the target # year listed based on the assumed removals for 2021-22. The SPR value for the ABC Rule is lower than 0.50 since this value represents the # average SPR value applied across the projection period based on the time-varying ",
#              label = "reb-options-catch",
#              align = 'l',
#              landscape = TRUE,
#              col_names = col_names)
```


\clearpage

## Rebuilding alternative time series 

```{r, results = 'asis'}

out = as.data.frame(cbind(round(reb[[1]]$prob_matrix[1:35, ],3)))
colnames(out)[10] = "ABC Rule"

table_format(x = out,
             caption = "Probability of recovery by year for rebuilding SPR alternatives assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "prob-mat",
             align = 'l',
             col_names = colnames(out))
```


```{r, results = 'asis'}

out = as.data.frame(cbind(round(reb[[1]]$acl_matrix[1:35, ],2)))
colnames(out)[10] = "ABC Rule"

table_format(x = out,
             caption = "Median catches (mt) by year for rebuilding SPR alternatives assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "acl-mat",
             align = 'l',
             col_names = colnames(out))
```


```{r, results = 'asis'}

out = as.data.frame(cbind(round(reb[[1]]$ofl_matrix[1:35,],2)))
colnames(out)[10] = "ABC Rule"

table_format(x = out,
             caption = "Median ABCs (mt) by year for rebuilding SPR alternatives assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "ofl-mat",
             align = 'l',
             col_names = colnames(out))
```


```{r, results = 'asis'}

out = as.data.frame(cbind(round(reb[[1]]$relativeb_matrix[1:35,],2)))
colnames(out)[10] = "ABC Rule"

table_format(x = out,
             caption = "Median spawning output relative to the 40 percent of unfished spawning output target by year for rebuilding SPR alternatives assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively. ",
             label = "rel-ssb-mat",
             align = 'l',
             col_names = colnames(out))
```

\clearpage

## Rebuilding alternative time series for high SPR harvest rates

```{r, results = 'asis'}

out = as.data.frame(round(reb[[2]]$prob_matrix[1:35, ],2))

table_format(x = out,
             caption = "The probability of rebuilding for additional SPR harvest rates assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "prob-mat-year",
             align = 'l',
             col_names = colnames(out))
```

```{r, results = 'asis'}

out = as.data.frame(round(reb[[2]]$acl_matrix[1:35, ],2))

table_format(x = out,
             caption = "Median catches (mt) by year for additional SPR harvest rates assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "acl-mat-year",
             align = 'l',
             col_names = colnames(out))
```

```{r, results = 'asis'}

out = as.data.frame(round(reb[[2]]$ofl_matrix[1:35, ],2))

table_format(x = out,
             caption = "Median ABCs (mt) by year for additional SPR harvest rates assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "ofl-mat-year",
             align = 'l',
             col_names = colnames(out))
```


```{r, results = 'asis'}

out = as.data.frame(round(reb[[2]]$relativeb_matrix[1:35, ],2))

table_format(x = out,
             caption = "Median spawning output relative to the 40 percent of unfished spawning output target by year for additional SPR harvest rates assuming removals of 90.8 and 88.9 mt in 2021 and 2022, respectively.",
             label = "rel-ssb-mat-year",
             align = 'l',
             col_names = colnames(out))
```


\clearpage


```{r, results = 'asis'}

#out = as.data.frame(cbind(round(reb[[2]]$prob_matrix[1:35, 1:9],3), round(reb[[5]]$prob_matrix[1:35, 10])))
#colnames(out)[10] = "ABC Rule"
#
#table_format(x = out,
#             caption = "Probability of recovery by year for rebuilding SPR alternatives assuming removals of 50 mt in 2021 and 2022, respectively.",
#             label = "prob-mat-catch",
#             align = 'l',
#             col_names = colnames(out))
```


```{r, results = 'asis'}

#out = as.data.frame(cbind(round(reb[[2]]$acl_matrix[1:35, 1:9],2), round(reb[[2]]$acl_matrix[1:35, 10],2)))
#colnames(out)[10] = "ABC Rule"
#
#table_format(x = out,
#             caption = "Catches (mt) by year for rebuilding SPR alternatives assuming removals of 50 mt in 2021 and 2022, respectively.",
#             label = "acl-mat-catch",
#             align = 'l',
#             col_names = colnames(out))
```

```{r, results = 'asis'}

#out = as.data.frame(cbind(round(reb[[2]]$ofl_matrix[1:35, 1:9],2), round(reb[[2]]$ofl_matrix[1:35, 10],2)))
#colnames(out)[10] = "ABC Rule"
#
#table_format(x = out,
#             caption = "OFLs (mt) by year for rebuilding SPR alternatives assuming removals of 50 mt in 2021 and 2022, respectively.",
#             label = "ofl-mat-catch",
#             align = 'l',
#             col_names = colnames(out))
```


```{r, results = 'asis'}

#out = as.data.frame(cbind(round(reb[[2]]$relativeb_matrix[1:35, 1:9],2), round(reb[[2]]$relativeb_matrix[1:35, 10],2)))
#colnames(out)[10] = "ABC Rule"
#
#table_format(x = out,
#             caption = "Spawning output relative to the 40 percent of unfished spawning output target by year for rebuilding SPR alternatives assuming #removals of 50 mt in 2021 and 2022, respectively.",
#             label = "rel-ssb-mat-catch",
#             align = 'l',
#             col_names = colnames(out))
```
