## Fishery-Dependent Data

### Commercial Fishery

#### Landings

The commercial removals were extracted from the The Pacific Fisheries Information Network (PacFIN) database for 1981-2020 on February 21, 2021. Commercial removals for `r spp` were combined into a single fleet by aggregating across gear types (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). Commercial landings prior to 1969 were extracted from the SWFSC catch reconstruction database for estimates from the California Catch Reconstruction [@ralston_documentation_2010]. Landings in this database are divided into trawl, non-trawl, and unknown gear categories. Regions 7 and 8 as defined by Ralston et al. [-@ralston_documentation_2010] were assigned to Southern California. Region 6 in Ralston et al. [-@ralston_documentation_2010] includes Santa Barbara County (mainly south of Point Conception), plus some major ports north of Point Conception. To allocate catches from Region 6 to the areas north and south of Point Conception, we followed an approach used by Dick et al. [-@dick_status_2007] for the assessment of cowcod. Specifically, port-specific landings of total rockfish from the CDFW Fish Bulletin series were used to determine the annual fraction of landings in Region 6 that was south of Point Conception (Table \ref{tab:com-ratio}). Rockfish landings at that time were not reported at the species level. Although the use of total rockfish landings to partition catch in Region 6 is not ideal, we see this as the best available option in the absence of port-specific species composition data. Years with no data were imputed using ratio estimates from adjacent years. Annual catches from unknown locations (Region 0) and unknown gear types were allocated proportional to the catches from known regions and gears. Catches from known regions, but unknown gears, were allocated proportional to catches by known gears within the same region. In this way, total annual removals in California were kept consistent with those reported by Ralston et al. [-@ralston_documentation_2010], and assigned to the assessment areas north and south of Point Conception.

In September 2005, the California Cooperative Groundfish Survey (CCGS CALCOM) incorporated newly acquired commercial landings statistics from 1969-80 into CALCOM database. The data consisted of landing receipts ("fish tickets"), including mixed species categories for rockfish. In order to assign rockfish landings to individual species, the earliest available species composition samples were applied to the fish ticket data by port, gear, and quarter. These 'ratio estimator' landings are coded (internally) as market category 977 in the CALCOM database, and are used in this and past assessments as the best available landings for the time period 1969-1980 for all port complexes.  See Appendix A of Dick et al. [-@dick_status_2007] for further details.
 
Commercial fishery landings from 1981-2020 were extracted from the PacFIN database (extracted February 22, 2021). Landings were separated for the area south of Point Conception based on port of landing. The input catches in the model represent total removals: landings plus discards.  Discards totals for the commercial fleet from 2002-2019 were determined based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide observed discards were allocated to state and area based on the total observed landings observed by WCGOP. The historical commercial discard mortality used to adjust the landings data to account for total removals was calculated based on the average coastwide discard rates from WCGOP of 4.4 percent. 

#### Length Compositions

Biological data were extracted from the PacFIN Biological Data System on February 21, 2001. Length data for the commercial fleet were extracted from the PacFIN Biological Data System (BDS) with samples for south of Point Conception beginning in 1983 (Table \ref{tab:com-len-samps}). The number of total lengths available was highly variable ranging from 2 to 542 samples per year. The samples prior to 1995 were sparse and variable across sizes. During model explorations these low sample years appeared to have a disproportionate impact on selectivity estimates and were therefore removed from the base model (treated as a 'ghost' fleet, see [Appendix A](#append_a) for implied fits to these lengths). 

The majority of lengths observed by the commercial fleet were between approximately 25 - 45 cm (Figure \ref{fig:com-len-data}), with relatively low observations of fish larger than 45 cm (detailed length compositions by year can be found in the Appendix, Section \ref{length-data}. The mean length observed by year ranged between 32 - 39 cm (Figure \ref{fig:mean-com-len-data}). The mean length across commercial lengths was the smallest in 2014 (around 32 cm) and has generally incrementally increased in the subsequent years.

The input sample sizes were calculated via the Stewart method (Ian Stewart, personal communication) based on a combination of trips and fish sampled:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}


### Recreational Fishery

#### Landings

The recreational fishery is the main source of exploitation of `r spp`. The recreational catches of `r spp` south of Point Conception in California waters peaked in the late 1970s and early 1980s. Removals declined in the 1990s and early 2000s.  The removals remained relatively low until 2015 and after.  The increase in removals in 2015 was likely due to new Annual Catch Limits being updated based on the 2013 assessment [@cope_data-moderate_2013].

Recreational removal estimates from 1928 to 1980 were obtained from the historical reconstruction [@ralston_documentation_2010], which were available split north and south of Point Conception. Recreational removals from 1981 - 1989 and 1993 - 2003 were obtained from Marine Recreational Fisheries Statistics Survey (MRFSS). MRFSS includes estimates of removals for 1980. However, due to inconsistencies in the estimates of this year in MRFSS, likely due to it being the first year of the survey with low sample sizes, the value for recreational removals from Ralston et al. [-@ralston_documentation_2010] was used.

The MRFSS definition of "Southern California" included San Luis Obispo County from 1981 - 1989, requiring the catches from this county to be split out and removed from the recreational removals south of Point Conception. Albin et al. [-@albin_effort_1993] used MRFSS data to estimate catch at a finer spatial scale from the California/Oregon border to the southern edge of San Luis Obispo County. The ratio of catches (0.316) in San Luis Obispo to the total removals calculated based on the data from Albin et al. [-@albin_effort_1993] was estimated and used to adjust the MRFSS catches to account for the removals north of Point Conception. 

There are three years without removals, 1990 - 1992, available in the MRFSS data. Removals for the missing years were filled in by applying a linear ramp in removals between the 1989 and 1993 values. 

Recreational landings from 2004 - 2020 were obtained from California Recreational Fisheries Survey (CRFS available on the Recreational Fisheries Information Network, RecFIN). Both data sources, MRFSS and CRFS, provide total mortality which combined observed landings plus estimates of discarded fish.  

The recreational removals from the historical reconstruction from 1928 - 1980 account for only landed fish. A historical discard rate of 3 percent based on Miller and Gotshall [-@miller_ocean_1965] was used to estimate total catches for this period. MRSS and CRFS  each provide estimates of total mortality so no additional discard assumptions were made. 

#### Length Compositions

Length data for retained catch from MRFSS (1980-2003) and CRFS (2004-2020) were downloaded from the RecFIN website. Recreational length data were available starting in 1980 (Table \ref{tab:len-samps}).  The length data from the recreational fleet generally ranged between 25 to approximately 45 cm (Figure \ref{fig:rec-len-data}), with limited observations of fish greater than 45 cm. The annual mean length observed was relatively stable between 2004 and 2011, followed by a minor dip in mean size and slight increase in recent years (Figure \ref{fig:mean-rec-len-data}). Detailed length compositions by year can be found in the Appendix, Section \ref{length-data}.

The input sample sizes for the recreational length data were set equal to the number of length samples available by year. 