## Fishery-Independent Data

### NWFSC Hook and Line Survey

Since 2004, the NWFSC has conducted an annual hook and line survey targeting shelf rockfish in the genus *Sebastes* at fixed stations (e.g., sites, Figure \ref{fig:hkl-sites}) in the Southern California Bight. Key species of rockfish targeted by the `r hkl` are bocaccio (*S. paucispinis*), cowcod (*S. levis*), greenspotted (*S. chlorostictus*), and vermilion/sunset (*S. miniatus* and *S. crocotulus*) rockfishes, although a wide range of rockfish species have been observed by this survey. During each site visit, three deckhands simultaneously deploy 5-hook sampling rigs (this is referred to as a single drop) for a maximum of 5 minutes per line, but individual lines may be retrieved sooner at the angler's discretion (e.g., to avoid losing fish). Five drops are attempted at each site for a maximum possible catch of 75 fish per site per year (3 anglers x 5 hooks x 5 drops). Further details regarding the sample frame, site selection, and survey methodology are described by Harms et al. [-@harms_noaa_2008]. 

`r Spp` have been observed at multiple sampling sites by the `r hkl` each year between 2004 - 2019 (Table \ref{tab:hkl-len}).  Starting in 2014 the `r hkl` added sampling sites located within the cowcod conservation area (CCA). Across all sample years and sample sites the `r hkl`  has observed a total of 1,117 `r spp`.  `r Spp` have been observed both outside and inside the CCA (Figures \ref{fig:hkl-site-ob} and \ref{fig:hkl-cca}).  However, the limited number of `r spp` observations within the CCA constrained the ability to determine whether the CCA impacted the frequency and or sizes observed compared to the other areas sampled (non-CCA sampling sites). `r Spp` were observed at sites with depth ranging between 40 - 120 m with only the largest sizes being observed at the greatest depths (Figure \ref{fig:hkl-len-dep}).

`r Spp` caught in the `r hkl` were generally between 30 and 50 cm for both sexes (Figure \ref{fig:hkl-len-data}). The mean length observed by year was variable with an appreciable drop in the mean sized observed in 2012 but has gradually increased in the subsequent years (Figure \ref{fig:mean-hkl-len-data}). Detailed length compositions by year can be found in the Appendix, Section \ref{length-data}. The input sample sizes for the composition data were set equal to the number of length samples available by year. 

While `r spp` are not observed in large numbers similar to vermilion/sunset rockfish (N = 23,110), greenspotted rockfish (N = 4,432), or bocaccio (N = 16,519) in the `r hkl`, there are observations per year to support an index of abundance although it may be uncertain. An annual index of abundance was calculated from the `r hkl` data following the methods put Harms et al. [-@harms_analysis_2010] based on the AIC criterion. The index of abundance was calculated using a binomial generalized-linear model. The final index includes year, site, number of hooks, fisher, drop number, and swell height as covariates.  The single index of abundance was calculated using observations from both outside and within the CCA (Table \ref{tab:hkl-index-vals} and Figure \ref{fig:hkl-index}). Due to the limited number of `r spp` observations within the CCA, calculating an index of abundance using only data collected outside the CCAs was similar in trend and variance to the index calculated when using all available data. The diagnostics for the binomial generalized-linear model are shown in Figure \ref{fig:hkl-diag}. 


### NWFSC West Coast Groundfish Bottom Trawl Survey

The \gls{s-wcgbt} is based on a random-grid design; covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

The observations of `r spp` by the \gls{s-wcgbt} were limited (Table \ref{tab:wcgbts-len}). The \gls{s-wcgbt} uses trawl gear to sample sandy bottom areas off the West Coast and _a priori_ it would not be expected to be an informative data source for `r spp`, which are closely associated with rock substrate. The \gls{s-wcgbt} had  limited tows by year where `r spp` were observed within this area, preventing the calculation of an index of abundance for `r spp`. With limited length observations and in the absence of an index of abundance to link these data to, this data set was not used in the base model.





