# Assessment Model

## Summary of Previous Assessments 

`r Spp` was last assessed in 2013 [@cope_data-moderate_2013]. The stock was assessed using extended depletion-based stock reduction analysis (XDB-SRA) a data-moderate approach which incorporated catch and index data with prior on select parameters (natural mortality, stock status in a specified year, productivity, and the relative status of maximum productivity). `r Spp` was assessed as two separated stocks, the area south of Point Conception off the California coast and the area north of Point Conception to the Washington Canada border. The 2013 assessment estimated the stock south of Point Conception at 75 percent of unfished spawning output north of Point Conception at 48 percent of unfished spawning output. 

### Bridging Analysis

A bridging analysis was done to replicate the results from XDB-SRA.  XDB-SRA is a delay-difference model that uses a production function to define biomass and dynamics of a stock. XDB-SRA does not explicitly parameterize weight-at-length or length-at-age. The bridge Stock Synthesis (SS) model assumed a structure similar to XDB-SRA: single-sex, deterministic recruitment, knife-edged selectivity equal to 50 percent maturity-at-length. The growth in the bridge SS model was based on the biology values provided in the 2013 assessment for copper rockfish [@cope_data-moderate_2013], although the XDB-SRA does not explicitily define growth. The SS model used the data from the XDB-SRA model: catches and indices, the median parameter values from XDB-SRA:  depletion in the year 2000 and natural mortality, and productivity (parameterized via the 3-parameter Ricker Power stock-recruitment function). The SS model replicated the stock status time series from XDB-SRA, but the SS model resulted in a lower stock size time series compared to XDB-SRA (Figure \ref{fig:bridge-1}, red line).  This mis-match in scale alone implied a difference in the implied growth (all mature biomass assumed equal) within XD-SRA versus the weight-at-length parametization for SS. The female weight-at-length was adjusted within SS to produce a stock trajectory that matched in scale the results from XDB-SRA (Figure \ref{fig:bridge-1} and \ref{fig:bridge-growth}).

Once the matching SS structure was identified, the parameterization of the model was updated in a step-wise fashion by the following steps:

\begin{enumerate}
	\item Remove the depletion "survey" for the year 2000.
	\item Update all biology to match those applied in the base model (natural mortality, length-weigth, length-at-age, fecundity, and maturity).
	\item Switch to a Beverton-Holt stock-recruitment relationship with a steepness value of 0.72, the value in the base model.
	\item Update catches through 2012, lumped into a single fleet.
	\item Add all lengths to the model through 2012, lumped into a single fleet. Allow for asymptotic selectivity estimation using the double normal selectivity parameterization. 
	\item Remove the indices of abundance (fishery dependent - CPFV, CDFW Observer Program) from the XDB-SRA 2013 model.
	\item Add in the NWFSC Hook and Line index of abundance, length data, and fleet specific selectivity curve.
	\item Separate catches and lengths into the fleet structure assumed in the base model. Allow for fleet specific selecitivy estimation.  
	\item Turn on annual recruitment deviations.
\end{enumerate}     

Removing the depletion survey resulted in a shift upward in scale and stock status in 2013 (Figures \ref{fig:bridge-ssb} and \ref{fig:bridge-depl}). Updating the biology included changing the fecundity assumption from it being equal to spawning biomass to in terms of eggs and body size (spawning output). Figure \ref{fig:bridge-ssb-2} shows only the time series in terms of spawning output for ease of visability. The comparable quantity, stock status, was more pessimistic relative to the 2013 XDB-SRA model (Figure \ref{fig:bridge-depl}). All subsequent changes or additions to the 2013 model resulted in a more pessimistic view of the stock (Figure \ref{fig:bridge-depl}). The largest changes resulted when the length composition data was added and the 2013 fishery-dependent indices removed.  The fishery-dependent indices used in the 2013 `r spp` south model were variable but had a slight increasing trend (see Figure 69 in  Cope et al. [-@cope_data-moderate_2013]).  In contrast, the length data from the recreational fishery, the main source of removals, has limited observation of larger `r spp` with the peak of the length data distribution around 30 cm. The observed length distribution combined with an asymptotic selectivity assumption resulted in an extreme estimate of stock status.  

The bridge model was modified from this point to determine the base model by extending the catches, the index of abundance, and fishery and survey lengths to 2020 along with updating and/or changeing model assumptions based upon fits to the data.  

## Model Structure and Assumptions

The south of Point Conception `r spp` area assessed using a two-sex model with sex specific life history parameters.  The model assumed two fishings fleets: 1) commercial and 2) recreational fleets with removals beginning in `r startyr` and one survey fleet, `r hkl`.  Selectivity was specified for all fleets in the model using the double normal parameterization within SS. The selectivity for the commercial and recreational fleets were allowed to estimate dome-shaped selectivity and the `r hkl` selectivity was fixe to be asymptotic. 


### Modeling Platform and Structure

SS version 3.30.16 was used to estimate the parameters in the model. The R package [r4ss](https://github.com/r4ss/r4ss), version 1.38.0, along with R version 4.0.1 were used to investigate and plot model fits. 

### Priors

```{r, echo=FALSE, results='asis'}
general_wd = "C:/Assessments/2021/copper_rockfish_2021/write_up/general_text"
filein = file.path(general_wd,'model_priors.Rmd')
read_child(filein)
```  

### Data Weighting

Length composition data for the comercial fishery started with a sample size determined from the equation listed in Sections \ref{commercial-fishery}. The input sample size for the recreational fishery and `r hkl` length composition data were set equal to the number of length samples by year.   

The base  model was weighted using the "Francis method", which was based on equation TA1.8 in Francis [-@francis_data_2011]. This formulation looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Sensitivities were performed examing the difference in weighting using McAllister-Ianelli Harmonic Mean Weighting[-@mcallister_bayesian_1997] and the Dirichlet Multinomial Weighting [-@thorson_model-based_2017].

### Estimated and Fixed Parameters

There were 12 estimated parameters in the base model. These included 1 parameter for $R_0$, 1 for estimated added variance for the `r hkl` index, and 10 parameters for selectivity (Table \ref{tab:params}). The estimation of annual recruitment was explored but were not included in the base model due to correlation in catches.

Fixed parameters in the model were as follows. Steepness was fixed at `r print(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)`.  Natural mortality was fixed at `r round(model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1","Value"],3)` yr^-1^ for females and males, which is the median of the prior.  Annual recruitment was deterministic predicted from the stock-recruitment curve. Growth, maturity-at-length, and length-at-weight was fixed as described above in Section \ref{data}. Likelihood profiles were conducted across steepness, natural mortality, and growth parameters to examine the impact of the selected fixed values in the model.

Dome-shaped selectivity was explored for all fleets within the model. Older `r spp` are often found in deeper waters and may move into areas that limit their availability to fishing gear. After explorations, the commercial and recreational fleets were both allowed to estimate dome-shaped selectivity due to extreme model estimates when forced to be asymptotic.  


## Model Selection and Evaluation

The base assessment model for `r spp` was developed to balance parsimony and realism, and the goal was to estimate a spawning output trajectory for the population of `r spp` off the Washington coast. The model contains many assumptions to achieve parsimony and uses many different sources of data to estimate reality. A series of investigative model runs were done to achieve the final base model.

## Area Specific Assessment Challenges
