## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in Table \ref{tab:referenceES}. Estimates of stock size and status over time are shown in Table \ref{tab:timeseries}. 

### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The $R_0$ was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. The selectivity for both the commercial and recreational fleets were estimated to be dome-shaped, with reduced selectivity for larger `r spp`. A dome-shaped selectivity was not anticipated *apriori*, however, forcing one or both to have asymptotic selectivity resulted in an extremely depleted stock status (3 percent with both fleets selectivity asymptotic). The highly pessimistic stock status was deemed to have limited plausibility given the ongoing high removals of `r spp` in recent years.  Multiple sensitivities were performed to examine the assumption of dome-shaped selectivity in the base model. The commercial fleet selectivity peaked at  `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_S_Commercial(1)', 'Value'], 2)` cm and decreased to low selectivity rates for larger `r spp`.  The recreational fleet selectivity peaked at smaller sizes relative to the commercial fleet with full selectivity occurring at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_S_Recreational(2)', 'Value'], 1)` cm.  The peak selectivity for both the commercial and recreational fleets were less than the length-at-50 percent maturity (`r round(model$parameters[model$parameters$Label == 'Mat50%_Fem_GP_1', 'Value'], 2)` cm). 

The `r hkl` was fixed to have asymptotic selectivity with full selection starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_NWFSC_HKL(3)', 'Value'], 1)` cm. The `r hkl` selectivity is markedly different compared to the commercial and recreational fleets. The reason for this difference was speculated to be due to possibly two factors: 1) the survey across years was sampling deeper waters that have until recently the recreational fishery did not have access to, and 2) many of the observations of large `r spp` by the `r hkl` were around areas that would likely require 3/4 day trip if not a full-day or overnight trip (i.e., Santa Rosa Island, San Miguel Island) which would put them out of range of 1/2 day-trip recreational fishing efforts (John Harms, personal communication, NOAA, NWFSC). 

The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. Annual recruitment deviations were not estimated in the base model due to confounding between recent high catches and estimated recruitment deviations. A rise in catches could be related to above average recruitment. However, when recruitment deviations were allowed to be estimated the model the estimates of annual recruitment deviations were positively biased in recent years in order to maintain the population estimate greater than 0. This issue was identified by conducted a long retrospective run combined with a plot that reflects the model estimated recruitment strength by year as data are removed. When all data were removed that would inform recent recruitment the recruitment deviations did not decline to 0, but remained positive (Figure \ref{fig:squid-rec}). The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. Annual recruits estimated directly from the stock-recruitment curve are shown in Figure \ref{fig:recruits}. 


### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial, recreational, and `r hkl` fleets. Annual length composition fits are shown in [Appendix A](#append_a).  

The Pearson residuals for the commercial fishery length data area shown in Figure \ref{fig:com-pearson}. There are limited patterns in the Pearson residuals but there is potential evidence of an above average recruitment moving through the population in recent years. The mean length observed by year from the commercial fleet were uncertain but with a relatively stable mean size until 2014 when the mean length declined and then slowly increase in the subsequent years (Figure \ref{fig:com-mean-len-fit}).  

The Pearson residuals for the recreational length data are variable by year (Figure \ref{fig:rec-pearson}). Pearson residuals were positive, observations greater than expected, for larger fish prior to 2000. Adding a block in selectivity for this period was explored during model development but there was little support in the data for the added model complexity (e.g., similar fits to the data). In recent years there are patterns of above average recruitments moving through the population. The mean length in the early period of data ranged between 28 - 38 cm, with a decline and stabilizing of the mean observed length in recent years around 30 cm (Figure \ref{fig:rec-mean-len-fit}). 

The Pearson residuals for the `r hkl` were variable by year and observation by sex (Figure \ref{fig:hkl-pearson}). Similar to the other data sources in the model there appears to be a pattern of observations greater than the model expectations moving through the population possibly supporting an above average recruitment event prior to 2011 and 2013. The mean length observed by year from the `r hkl` varied by year ranging between 35 - 40 cm (Figure \ref{fig:hkl-mean-len-fit}). 

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}.  The model fits the aggregated lengths for both the commercial and recreational fleet length data generally well. 

The fit to the `r hkl` index of abundance is shown in Figure \ref{fig:index-fit}. The index of abundance was relatively flat between 2004 - 2009, drops in 2010, and then slow increases until 2015. The model estimated `r round(model$parameters[model$parameters$Label == "Q_extraSD_NWFSC_HKL(3)","Value"],2)` of added variance in order to fit the `r hkl` index of abundance. The large added variance was likely due to the limited observations of `r spp` by year by the survey (Table \ref{tab:hkl-len}).

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The estimated spawning output decreases sharply in the mid-1970s reaching a low around 2000. The spawning output slowly increases between 2000 - 2013 and then begins declining in recent years due to an increase in removals starting in 2013. The estimate of total biomass shows a similar pattern over time (Figure \ref{fig:tot-bio}).

The model estimates that the spawning output relative the unfished equilibrium spawning output declined below the current management threshold limit of 25 percent around 1983 and remained below the limit until 2011, and then dropping below the limit once again in 2016 (Figure \ref{fig:depl}). The relative stock status at the start of `r endyr + 1` is estimated to be below the rockfish relative biomass target of 40 percent (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`) and below the management threshold limit of 25 percent.   


### Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr` spawning output relative to unfished equilibrium spawning output is below the management threshold limit of 25 percent of unfished spawning output (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, has been above the harvest rate limit ($SPR_{50\%}$) in recent years, except 2020 when overall removals declined due to impacts of COVID-19 which reduced recreational fishing effort (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.

