\clearpage
# Figures



<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_figs, "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	
	


<!-- ====================================================================== -->
<!-- ****************   Commercial Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page2.png"), 
caption = "Length composition data from the commercial fleet",
label = 'com-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_CA_S_Commercial.png"), 
caption = "Mean length for commercial fleet with 95 percent confidence intervals",
label = 'mean-com-len-data')
```

<!-- ====================================================================== -->
<!-- **************** Recreational Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt0_page3.png"), 
caption = "Length composition data from the recreational fleet",
label = 'rec-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_CA_S_Recreational.png"), 
caption = "Mean length for recreational fleet with 95 percent confidence intervals",
label = 'mean-rec-len-data')
```

<!-- ====================================================================== -->
<!-- ************** NWFSC HKL Index & Length Sample  ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "plots",  "Map_HL_Sites_lndscp.jpg"), 
caption = "NWFSC Hook and Line sampling sites where yellow sites indicate locations inside Cowcod Conservation Areas. Additionally, known substrate structure, depths, and areas under various management regulations are shown for the area south of Point Conception",
label = 'hkl-sites')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "plots",  "HKL_Site_Observations.png"), 
caption = "NWFSC Hook and Line sample sites inside and outside the CCA and site with observations of copper rockfish",
label = 'hkl-site-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "hkl_cca_comparison.png"), 
caption = "NWFSC Hook and Line observations by year outside and inside the cowcod conservation area",
label = 'hkl-cca')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "plots",  "HKL_Size_by_Depth.png"), 
caption = "Lengths observations by depth in the NWFSC Hook and Line data",
label = 'hkl-len-dep')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt3mkt0.png"), 
caption = "Length composition data from the NWFSC Hook and Line fleet",
label = 'hkl-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_NWFSC_HKL.png"), 
caption = "Mean length for NWFSC Hook and Line fleet with 95 percent confidence intervals",
label = 'mean-hkl-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_figs, "hkl_index.png"), 
caption = "Index of abundance for the NWFSC Hook and Line survey. Lines indicate 95 percent uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'hkl-index')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "Copp.2019.NFT.1m.ALL",  "Copp.ALL.GAM.Fig.png"), 
caption = "Diangostics for the binomial generalized-linear model",
label = 'hkl-diag')
```

<!-- ====================================================================== -->
<!-- *************************     ROV         **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "rov",  "copper_socal_open_area.png"), 
caption = "Length frequency distribution in each 10 fm depth bin for copper rockfish sampled by the ROV in reference locations open to fishing south of Point Conception",
label = 'rov-open')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "rov",  "copper_socal_mpa_area.png"), 
caption = "Length frequency distribution in each 10 fm depth bin for copper rockfish sampled by the ROV in marine protected areas where retention is prohibited",
label = 'rov-mpa')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "rov",  "copper_socal_percent_open.png"), 
caption = "Percent composition of copper rockfish length frequency in 5 cm size classes for each 10 fm depth bin from ROV observations south of Point Conception in reference locations where retention is allowed",
#width = 150,
#height = 150,
label = 'rov-percent-open')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "rov",  "copper_socal_percent_mpa.png"), 
caption = "Percent composition of copper rockfish length frequency in 5 cm size classes for each 10 fm depth bin from ROV observations south of Point Conception in marine protected areas where retention is prohibited",
#width = 150,
#height = 150,
label = 'rov-percent-mpa')
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "doc_Length_Weight_Source.png"), 
caption = "Comparison of the length-at-weight data from the NWFSC Hook and Line and the NWFSC WCGBT surveys",
label = 'len-weight-survey')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "doc_Length_Weight_Sex.png"), 
caption = "Survey length-at-weight data with sex specific estimated fits",
label = 'len-weight')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "South_Len_at_Age.png"), 
caption = "Length-at-age for non-randomly sampled larger fish observed by the NWFSC Hook and Line and WCGBT survey",
label = 'survey-len-at-age-data')
```	


```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "doc_south_Age_by_Sex_Source.png"), 
caption = "Length-at-age for non-randomly sampled larger fish observed by the NWFSC Hook and Line and WCGBT survey and young fish from Lea",
label = 'south-len-at-age-data')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "South_Data_Comparison_Len_at_Age.png"), 
caption = "Length-at-age comparisons between survey collected fish south of Point Conception and to those observed off the coast of Oregon and Washington",
label = 'len-at-age-comp')
```	

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Length-at-age in the beginning of the year with the coefficient of variation by age within the model",
label = 'len-age-ss')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of  length",
label = 'maturity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_fraction_female.png"), 
caption = "Fraction female by length across all available data sources",
label = 'len-sex-ratio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Age_fraction_female.png"), 
caption = "Fraction female by age across all available data sources",
label = 'age-sex-ratio')
```

<!-- ====================================================================== -->
<!-- *********************  Model Bridging          ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
loc = "C:/Assessments/2021/copper_rockfish_2021/models/ca_s_pt_c/_bridge/_plots"
add_figure(
filein = file.path(loc, "Initial_Bridge.png"), 
caption = "Comparison between SS bridge model and the results from the 2013 XDB-SRA model",
label = 'bridge-1')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(loc, "Growth.png"), 
caption = "Adjustment to SS female weight-at-length curve to create a match in stock scale to XDB-SRA",
label = 'bridge-growth')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(loc, "1_bridge_all_compare1_spawnbio.png"), 
caption = "The time series of spawning biomass (or output) for updates to the 2013 model",
label = 'bridge-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(loc, "1_bridge_all_compare3_Bratio.png"), 
caption = "The time series of fraction unfished for updates to the 2013 model",
label = 'bridge-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(loc, "1_bridge_subset_compare1_spawnbio.png"), 
caption = "The time series of spawning output for the subset of bridge models with the updated fecundity relationship",
label = 'bridge-ssb-2')
```


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_figs, "selectivity.png"),
caption = "Selectivity at length by fleet",
label = 'selex')
```


<!-- ====================================================================== -->
<!-- *********************    Recruitment            ********************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path("//nwcfile/FRAM/Assessments/CurrentAssessments/DataModerate_2021/copper_rockfish/models/ca_s_pt_c/10.0_base_retro", "Squid_RecDevs.png"), 
caption = "The estimated recruitment deviations as additional years of data are removed during a retrospective run. Select years of estimated recruitment deviations remain greater than 0 after all informative data are removed",
label = 'squid-rec')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt0_page2.png"), 
caption = "Pearson residuals for commercial fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'com-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_CA_S_Commercial.png"), 
caption = "Mean length for commercial lengths with 95 percent confidence intervals based on current samples sizes",
label = 'com-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt0_page3.png"), 
caption = "Pearson residuals for recreational fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_CA_S_Recreational.png"), 
caption = "Mean length for recreational lengths with 95 percent confidence intervals based on current samples sizes",
label = 'rec-mean-len-fit')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt3mkt0.png"), 
caption = "Pearson residuals for NWFSC Hook and Line survey. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'hkl-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_NWFSC_HKL.png"), 
caption = "Mean length for recreational lengths with 95 percent confidence intervals based on current samples sizes",
label = 'hkl-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"),
caption = "Aggregated length comps over all years",
label = 'agg-len-fit')
```

<!-- ====================================================================== -->
<!-- **************      NWFSC HKL Index Fit         ********************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}

add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_NWFSC_HKL.png"),
caption = "Fit to index data for the NWFSC Hook and Line survey",
label = 'index-fit')
```

<!-- ====================================================================== -->
<!-- ******************      Time Series       **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_figs, "unavailable_biomass.png"), 
caption = "Estimated time series of unavailable spawning output",
label = 'ssb-unavailable')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Fraction_of_unfished_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning output",
label = 'depl')
```


<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->
  
```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_1_compare2_spawnbio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb-1')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_1_compare4_Bratio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl-1')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_2_compare2_spawnbio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb-2')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_2_compare4_Bratio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl-2')
```

\newpage

<!-- ====================================================================== -->
<!-- ******************  Area Sensitivities   ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_area_compare2_spawnbio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity examining alternative percent of the population protected from fishing",
label = 'sens-area-ssb')
```

```{r, echo=FALSE, results='asis'}
nm = paste0(basename(mod_loc), "_area_compare4_Bratio_uncertainty.png")
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity examining alternative percent of the population protected from fishing",
label = 'sens-area-depl')
```

\newpage


<!-- ====================================================================== -->
<!-- ******************      Likelihoods      ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'figures_likelihoods.Rmd')
read_child(filein)
```

\clearpage

<!-- ====================================================================== -->
<!-- ******************       LB-SPR          ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
lbspr = "C:/Assessments/2021/copper_rockfish_2021/models/lbspr"

add_figure(
filein = file.path(lbspr, "Copper_SoCAL_YrEsts_newVBGF.png"), 
caption = "LB-SPR yearly estimates of selectivity, the ratio of fishing intensity to natural mortality (F/M), and annual spawner-per-recruit (SPR) values",
label = 'lbspr')
```

\newpage

<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->
  
```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'figures_retro.Rmd')
read_child(filein)
```

\newpage

<!-- ====================================================================== -->
<!-- ******************   Comparison with 2013  *************************** --> 
<!-- ====================================================================== -->
  
add_figure(
filein = file.path(getwd(), 'figs', "assess_compare_compare2_spawnbio_uncertainty.png"), 
caption = "The estimated spawning output from the base model and the 2013 assessment",
label = 'compare-ssb')
```

add_figure(
filein = file.path(getwd(), 'figs', "assess_compare_compare4_Bratio_uncertainty.png"), 
caption = "The estimated fraction unfished from the base model and the 2013 assessment",
label = 'compare-depl')
```

\newpage




<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estimated correlations between the biomass ratio and SPR ratio",
label = 'phase')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield')
```
