\clearpage

# Appendix A 

## Annual Length Composition Data 

```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "CompDat"), ]
plot.vec = grep("comp_lendat_flt", len_fit$label)
filein = file.path(mod_loc, "plots")
for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}
```

\newpage

## Detailed Fit to Length Composition Data 


```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "LenComp"), ]
plot.vec = grep("comp_lenfit_flt", len_fit$label)
filein = file.path(mod_loc, "plots")
for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}
```

## Implied Fit to Commercial 'Ghost' Fleet Length Data 


```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "LenComp"), ]
plot.vec = grep("comp_gstlenfit_flt1mkt0", len_fit$label)
filein = file.path(mod_loc, "plots")
for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}
```
